### ISSUE TITLE
working examples?

### ISSUE THREAD

**Issue by rajarsheem** [faneshion/MatchZoo#1]
Do you have any working examples that can help me know more about it ?

**Comment by faneshion** [comment]
We have build a working example for ad-hoc retrieval in the examples. You can try it.

**Comment by faneshion** [comment]
Thanks for your attention to our MatchZoo project. I am sorry to be so late to reply for you as I am traveling last week. We have build a working examples for DRMM on million query dataset. You can check the github. Any other questions are welcome~


________________________________
发件人: Rajarshee Mitra <notifications@github.com>
发送时间: 2017年7月28日 14:53
收件人: faneshion/MatchZoo
抄送: Subscribed
主题: [faneshion/MatchZoo] working examples? (#1)


Do you have any working examples that can help me know more about it ?

―

**Comment by rajarsheem** [comment]
Can you give the link?

**Comment by loveJasmine** [comment]
where is the example

**Comment by 1264561652** [comment]
> 你能给出链接吗？

同问
