### ISSUE TITLE
classification predict label

### ISSUE THREAD

**Issue by hrdxwandg** [faneshion/MatchZoo#100]
Hi, in MatchPyramid  model, how can i convert the last column(score) to label.
some example  as follow:
1 T0 T1 0.45470667
1 T0 T910 0.2128342
1 T2 T3 0.35700366
1 T2 T22 0.34081152
0 T2 T1367 0.27757892

**Comment by yangliuy** [comment]
You can define a threshold the transfer the score to label. The threshold could be optimized by the validation data.

**Comment by hrdxwandg** [comment]
thanks. 
I read the code in main.py and run the demo QuoraQP, i could not find the place of threshold. in the demo QuoraQP how to compute the accuracy? for binary classification,  only need to use np.argmax() get the index for label?

**Comment by bwanglzu** [comment]
@hrdxwandg 
QuoraQP is evaluated with accuracy, then it will call `matchzoo/evaluation/metrics/evaluations.py`:

```python
def accuracy(y_true, y_pred):
    y_true = _to_list(np.squeeze(y_true).tolist())
    y_pred = _to_list(np.squeeze(y_pred).tolist())
    y_true_idx = np.argmax(y_true, axis = 1)
    y_pred_idx = np.argmax(y_pred, axis = 1)
    assert y_true_idx.shape == y_pred_idx.shape
    return 1.0 * np.sum(y_true_idx == y_pred_idx) / len(y_true)
```
