### ISSUE TITLE
Do it support the incremental training, load the pre-training model?

### ISSUE THREAD

**Issue by loveJasmine** [faneshion/MatchZoo#102]

**Comment by bwanglzu** [comment]
1. MatchZoo is built based on Keras.
2. At the moment, Keras do support transfer learning, (as far as I know) do not support online/incremental learning. 

But it doesn't mean that you can't achieve "online". If you do not care computational power, just re-train a network when new data comes in by implementing **periodic tasks**. The idea is:

1. You create a periodic task (say run a piece of code every X seconds) using simple [time module](https://stackoverflow.com/questions/8600161/executing-periodic-actions-in-python) or [celery task](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html).
2. Your piece of code is used for count number of samples.
3. If `current_number_samples > previous_number_samples`, fit a new model with MatchZoo.
