### ISSUE TITLE
Published results not getting reproduced

### ISSUE THREAD

**Issue by aneesh-joshi** [faneshion/MatchZoo#103]
Hi,
I am trying to reproduce the ndcg scores published on the readme
However, I am not getting similar numbers.

I run the `run_xxxx.sh` functions provided in `examples/wikiqa/`
On the prediction task, I get ndcg@3 values around 0.3 AS compared to the 0.5 to 0.6 range published.

Could I be doing something wrong?
Isn't running the network with `--predict` the correct way of getting there?

Example output:
`[05-16-2018 19:19:00]   [Predict] @ predict [Predict] results:  ndcg@3=0.379165 ndcg@5=0.451163 map=0.416128` for cdssm

and

`[05-17-2018 18:24:32]   [Predict] @ predict [Predict] results:  ndcg@3=0.341159 ndcg@5=0.415373 map=0.391363` for mvlstm

**Comment by aneesh-joshi** [comment]
@faneshion

**Comment by bwanglzu** [comment]
Same issue [here](https://github.com/faneshion/MatchZoo/issues/99)

**Comment by yangliuy** [comment]
@aneesh-joshi @bwanglzu See my reply [here] (https://github.com/faneshion/MatchZoo/issues/99)

**Comment by aneesh-joshi** [comment]
discussion going on in 
https://github.com/faneshion/MatchZoo/issues/99

So, closing
