### ISSUE TITLE
how to use multicore to do prediction?

### ISSUE THREAD

**Issue by loveJasmine** [faneshion/MatchZoo#104]
currently, I just see only one core used while prediction

**Comment by bwanglzu** [comment]
It's a programming problem instead of a MatchZoo problem.

PLEASE [GOOGLE](https://stackoverflow.com/questions/2846653/how-to-use-threading-in-python).

**Comment by bwanglzu** [comment]
Please check this [link](https://stackoverflow.com/questions/46725323/keras-tensorflow-exception-while-predicting-from-multiple-threads)

**Comment by bwanglzu** [comment]
Hope your question has been solved.
Best!
