### ISSUE TITLE
some question about MatchPyramid model

### ISSUE THREAD

**Issue by hrdxwandg** [faneshion/MatchZoo#112]
I read the source code about MatchPyramid model. I found there is only one convolutional layer and  one dynamic max-pooling layer. it is different from the paper's description. 
Am I right? or I understand wrong？
And how to implement two or more layers?

**Comment by ymzx** [comment]
Hi guys , I am jwduan,  a worker in ShangHai, I am studying the MatchPyramid now, as you, can we have wechat each other? "yemazhuxing" is mine.

**Comment by bwanglzu** [comment]
@hrdxwandg 
> We tried to implement the most important components/novel parts of these neural models. But it is still possible that there are some differences between our current implementation details with some details described in the paper. For some critical differences, we will fix them in the next version of MatchZoo.

For more information, please refer to this issue #99

**Comment by hrdxwandg** [comment]
@bwanglzu 
ok, thanks
