### ISSUE TITLE
What kind of model and feature is suitable for this scenery? (deal with synonym)

### ISSUE THREAD

**Issue by guotong1988** [faneshion/MatchZoo#113]
Train data: `Who is Michael Jordan? ` and `Who is Air Jordan? ` are one right match.
The test data is `Who is Jumpman Jordan? `  and `Who is Air Jordan? `

What feature should I add for training? Which model can capture the match info for this case?

Thank you！！！
@pl8787 @faneshion @yangliuy @HouJP @JiafengGuo

**Comment by bwanglzu** [comment]
@guotong1988 Can you clarify your question?

**Comment by yangliuy** [comment]
@guotong1988 I think your question is on training/testing of paraphrase identification. You test data should also contain a question pair, correct ? You can refer to the QuoraQP data in the readme file. PI is supported by MatchZoo.

**Comment by guotong1988** [comment]
Thank you. I have edit the question~

**Comment by bwanglzu** [comment]
@guotong1988 @yangliuy 's answer make sense for you?

**Comment by bwanglzu** [comment]
Thanks for your question, I'll close it for now. If you have further questions, please feel free to re-open it or create a new issue. Best.
