### ISSUE TITLE
how to do training and testing on different datasets

### ISSUE THREAD

**Issue by h3n0r1k** [faneshion/MatchZoo#114]
hello,

I am quite confused by the config file. We have a trainingset wich we want to use to train the model. Then we have another testingset, wich we want to use to evaluate the results. 
The confusing part is, there are topic1 and topic2 in the config file:

> "text1_corpus": "./data/toy_example/ranking/corpus_preprocessed.txt",
> "text2_corpus": "./data/toy_example/ranking/corpus_preprocessed.txt

What do I need to configure to use one dataset for training and one dataset for testing? 

Thanks in advance

**Comment by codingnoobneedshelp** [comment]
hey, i want to do the same. my train and test corpus have not the same length, so if i merge them and than run the function run_with_train_valid_test_corpus. how can i specify the parts it will split the relations? thanks for  your help mate.

**Comment by bwanglzu** [comment]
@codingnoobneedshelp @h3n0r1k Thanks for the question, we'll find appropriate person to answer this question asap.

**Comment by faneshion** [comment]
@codingnoobneedshelp, as you have said, you can use the method split_train_valid_test_for_ranking to split the dataset. If you want to train on one corpus and the test on another corpus. I recommend you to split the training data into train and validation. By the way, you can also train without validation by directly testing the test corpus.

**Comment by bwanglzu** [comment]
I'll close this issue for now, if you have further questions please feel free to re-open it or create a new issue. Best!
