### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#119]
**NOTICE: BEFORE SENDING A PR, PLEASE CREATE AN ISSUE FIRST, DISCUSS WITH US THEN CONTRIBUTE. SENDING PRs DIRECTLY TO OUR CODE BASE = WASTE YOUR & OUR TIME.**

Hi, ppls, today we officially introduced TravisCI into MatchZoo to get rid of technical debt.

If anyone happened to figure out any bug or enhancement, please follow this pipeline:

1. Fork the latest version of MatchZoo into your repo. (exclude core developers)
2. Create an issue under faneshion/Matchzoo, write the description of the bug/enhancement.
3. Clone your forked MatchZoo into your machine, edit code.
4. Run `make init` and `make test`  using terminal/command line, ensure dependency check & unit tests passed on your computer.
5. Push to your forked repo, send the pull request, in PR, you need to create a link to the issue you created using `#[issue_id]`, and describe what has been changed.
6. Wait CI passed.
7. Wait Codecov generate the coverage report.
8. We'll review the code and merge PR

Thanks!

**Comment by bwanglzu** [comment]
For core developers:

1. Create a sub-branch under `dev`, naming conventions:
    + For new features or enhancements, use `feature/[branch-name]`.
    + For bugs, use `hotfix/[branch-name]`
2. Create an issue under faneshion/Matchzoo, write the description of the bug/enhancement.
3. `git pull` to get the latest code, `git checkout feature/[branch-name]` to switch to you newly created branch.
4. Edit code.
5. Run `make init` and `make test` to ensure all the dependencies & unit tests has been passed.
6. Create a new PR, assign yourself as `assignees`, assign 1 or 2 `reviewers` to review your code.
7. Create a  link between your PR & Issue using `#[issue-id]`.
8. Wait  CI passed.
9. Wait all reviewers agreed this piece of code can be merged into the code base.
10.  IMPORTANT: USE `SQUASH AND MERGE` INSTEAD OF `MERGE`!
11. Close issue you created.
12. Remove sub-branch you created for this issue (i.e. `feature/branch-name` or `hotfix/branch-name`) locally and remotely.

**Comment by bwanglzu** [comment]
More:
1. we expect your code to be Pythonic, which means it should at least satisfy [PEP8](https://www.python.org/dev/peps/pep-0008/) standard (Don't worry we'll review your code).
2. We expect your code change has corresponded unit-test. Currently, we're using Unittest, later we might shift to pytest.

**Comment by thiziri** [comment]
Is it possible to create my own version and be updated automatically with different changes? If so, how can I get it?

**Comment by uduse** [comment]
@thiziri clone the repo, do your magic, and rebase onto the master once the master here updates.

**Comment by thiziri** [comment]
Yes, I'm still working the previous version, a lot of updates are made, now I've forked [my repo](https://github.com/thiziri/MatchZoo). If I understand, now, all that I have to do is:
1- do my magic (as you said)
2- commit to my repo
3- merge with [master](https://github.com/faneshion/MatchZoo)
Is that correct?

**Comment by bwanglzu** [comment]
@thiziri Haha now we're developing 2.0 version of MatchZoo! Most of the development will happen on branch 2.0 (serve as master).

**Comment by thiziri** [comment]
Do you mean [this one](https://github.com/faneshion/MatchZoo/tree/2.0)? There are not all the folders that are present in the master one. Do you mind give some clarifications, please ? how can I keep my repo up to date and contribute...? (my last question)

**Comment by thiziri** [comment]
Okay, thank you. I'll read this to learn more, then back here if I have other questions.
Thanks

**Comment by bwanglzu** [comment]
@thiziri no problem :)
