### ISSUE TITLE
ndcg@及map精度问题

### ISSUE THREAD

**Issue by MRuAyAN** [faneshion/MatchZoo#12]
你好，请原谅用中文，有几个问题不是很理解请教一下：
1. github中各模型所得的ndcg及map的数据与论文(A Deep Relevance Matching Model for Ad-hoc Retrieval)中的数据相差甚远, 与这些提出这些模型的论文也同样如此。是因为不同数据导致的么，不清楚是怎么回事呢？
2. 很多模型的实现并不是完全参照论文中的模型及超参数进行模型bulid的，这样用于论文数据的展示是否严谨？如ARCi模型卷积之后使用的是多层感知机，而代码中的arci模型直接接了一个softmax层。
3. classify的使用场景是什么呢？ 可否看成是ranking的一个特例。
感谢大师们的解答。

**Comment by faneshion** [comment]
1 当前github中的各个模型的结果是在WikiQA的数据下的结果，你说的相差甚远是指在哪个数据集上的结果？
2 模型的实现基本是按照论文的描述实现的，由于深度学习的模型针对不同数据集超参存在差异，因此我们也针对WikiQA的数据集调整了模型的超参，比如你提到的arci的网络，我们简化了多层的卷积层到一层、多层全连接到一层的全连接，以适用WikiQA数据集。其他的模型也都做了相应的调整。
3 classify的使用场景，比如说判断两句话是否表达同一个意思。在CQA的任务中很比较常用。

**Comment by MRuAyAN** [comment]
感谢解答，接上，还有以下几点不是很理解：
1. arci模型在推文回复的匹配上P@1的精度达到60%，而在上述提到的论文的Robust-04上的P@20的精度仅为6.5%，我知道测试数据不一样，但两者的精度相去甚远。
2. CQA的任务是什么任务呢？
3. drmm_tks是drmm模型的一个变种，但我看了论文感觉drmm_tks更贴近于论文中模型的构建，而drmm模型的bulid并不像论文中drmm。
继续感谢解答

**Comment by JiafengGuo** [comment]
1. 任务的不同导致模型不适用，ARCI适用于短文本语义匹配，对短查询和长文档的相关匹配表现不好。
2. CQA是指给定一个问答社区的数据，对一个新问题找到相似的提过的问题。
3. tks是只用最强的top k个信号，和drmm用全部信号的统计直方图不同。

**Comment by MRuAyAN** [comment]
好的，清楚了很多，感谢团队成员们的耐心解答。谢谢

**Comment by rgtjf** [comment]
很细致的解答！我也有一个问题期待解决一下：
1. 在实现ARC-II时，在做``Flatten``这步的时候，由于句子有padding, 最后会出现很多0项，之后再在后面加全连接层，会出现很多0。我当时实验下来效果不好，我想问一下你们是怎么解决的，在一开始padding的时候补的句子中的词吗？谢谢
https://github.com/faneshion/MatchZoo/blob/4431352bf62459f6b19c375690ff39173f20197f/matchzoo/models/arcii.py#L77-L84
