### ISSUE TITLE
what does  'label=2'  mean

### ISSUE THREAD

**Issue by pwlazy** [faneshion/MatchZoo#127]
i found there are rows where 'label=2' in file 'data/toy_example/ranking/relation_test.txt' and 'data/toy_example/ranking/relation_train.txt'

if 0 means 'not match', 1 means 'match', then 2 means?
is there another label such as 3,4,.......? and how many kinds of labels in the DRMM?

**Comment by faneshion** [comment]
In information retrieval, label can be multi-graded relevance. Thus, 0 means non-relevant, 1 means weak relevance, 2 means strong relevance.  You can refer to "https://dl.acm.org/citation.cfm?id=772464" to get more about multi-graded relevance in IR.

**Comment by bwanglzu** [comment]
@pwlazy Hope you question has been solved. I'll close this issue for now, best!
