### ISSUE TITLE
Integrate Codecov for 2.0 branch

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#128]
To ensure always 100% covered by unit tests.

[Codecov](https://codecov.io/gh)

@faneshion Need to add the repository to codecov. (like requires.io & TravisCI, it's free :)).

Python [example](https://github.com/codecov/example-python).

How it would helps:

For each Pull Request, 1. wait CI passed, 2. Wait CodeCov report generated and see whether it's 100% coverage (or at least percentage didn't decrease). 3. Wait all reviewers agree. 4. Squash and Merge.

It looks like:

![codecov](https://image.ibb.co/i5nqQy/1.png)

**Comment by uduse** [comment]
It's hard to cover 100% of the code when the code it not initially designed with testing in mind. e.g. `matchzoo.main.train` has many lines and many `if`s. One needs to do weird things to get that fully tested. I suggest achieving 90% or something first, and refactor the code in a future major release before we go for higher coverage.

**Comment by bwanglzu** [comment]
@uduse haha we're working on refactoring! I'd say the more the better :)
