### ISSUE TITLE
mtrand error: 'NoneType' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by h3n0r1k** [faneshion/MatchZoo#131]
hey, hoping someone can help me :)

After this code:

`python gen_w2v.py /home/ba/MatchZoo/data/toy_example/ranking/word_dict.txt /home/ba/MatchZoo/data/toy_example/ranking/glove.840B.300d.txt /home/ba/MatchZoo/data/toy_example/ranking/embed_glove_d300
`

I am getting this error: 

`2196017it [9:41:20, 62.96it/s]
load word vectors ...

Loading vectors from /home/ba/MatchZoo/data/toy_example/ranking/word_dict.txt
100%|████████████████████████████████████████████████████████████████| 212644/212644 [00:00<00:00, 1206949.69it/s]
Traceback (most recent call last):
  File "gen_w2v.py", line 129, in <module>
    embeddings = load_word_embedding(word_dict, w2v_file)
  File "gen_w2v.py", line 90, in load_word_embedding
    curr_embed = (2.0 * np.random.random_sample([dim]) - 1.0) * alpha
  File "mtrand.pyx", line 861, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
TypeError: 'NoneType' object cannot be interpreted as an index`

Word Vectors were successfully loaded before, then this error appears when trying to load the word dict. I tryed to reinstall numpy and some other packages but nothing helped. 

The word_dict file was produced by the preprocess.py and looks like this (Its just a little part of the Dict, it has 212644 lines):

> extrastress 190601
aceton 13407
autosom 5845
chemoradiotherapeut 14713
polarprob 71802
93,134 118825
opn/ca-125 203195
procavia 160607
pmit+ 135356
143,991 204032
noxious 20925
choedochoscop 163663
hhai. 203721
edelfosin 160238

Thanks for any help :)

**Comment by faneshion** [comment]
The order of parameters for gen_w2v.py is mistaken. For you case, it should be like this:
"python gen_w2v.py /home/ba/MatchZoo/data/toy_example/ranking/glove.840B.300d.txt  /home/ba/MatchZoo/data/toy_example/ranking/word_dict.txt /home/ba/MatchZoo/data/toy_example/ranking/embed_glove_d300".

**Comment by h3n0r1k** [comment]
Thanks for the help, that fixed it i guess. Now im getting 

> Killed

After nothing happening for a few minutes. Any suggestion on that?

**Comment by h3n0r1k** [comment]
Kern.log File says: "Out of memory: Kill process ....".

I got 12gb Ram, should this not be enough? Or is there any way around this Error?

Thanks in advance

**Comment by faneshion** [comment]
This happened in generating the word embedding map file ? How many words in you word_dict.txt?

**Comment by h3n0r1k** [comment]
Yes, 212644 words

**Comment by faneshion** [comment]
You can try to reduce the vocabulary size. Specifically, you can remove low frequency words.

**Comment by h3n0r1k** [comment]
Even getting killed when only using a size of 10 words, and i looked at the memory monitor wich fills up to 100% and shortly after the killed happens

**Comment by bwanglzu** [comment]
Strange

**Comment by bwanglzu** [comment]
So your memory is not sufficient to load embedding

**Comment by codingnoobneedshelp** [comment]
So how much memory do you guys have to load the glove.840B.300d.zip vectors?

**Comment by bwanglzu** [comment]
Thanks for your question, I'll close it for now. If you have further questions, please feel free to re-open it or create a new issue. Best.

We'll think a smarter way to load embeddings in the next version, thanks!
