### ISSUE TITLE
wechat

### ISSUE THREAD

**Issue by hshrimp** [faneshion/MatchZoo#14]
Your Wechat MatchZoo Group is full, and i can't join you, could you please take me in. My wechat number is : _hshrimp_. Thank you.

**Comment by yliuhb** [comment]
me,too. My wechat number is : yliuhb. Thank you.

**Comment by faneshion** [comment]
I have invited both you two, please check in wechat.

**Comment by StKlaas** [comment]
me too... My wechat number is: justlcj7. Thank you.

**Comment by rgtjf** [comment]
hi, could you please take me in the wechat group. (wechat id: jsrgtjf)? Thanks a lot.

**Comment by xieydd** [comment]
me,too. My wechat number is : 13253537292. Thank you.

**Comment by faneshion** [comment]
We have applied another wechat number: CLJ_Keep. Any one who want to join the group and add this number. Please show me the detail information about your name and school/company when applying.

**Comment by StKlaas** [comment]
@faneshion is it a wechat ID?  I looked it up in the App but found nothing. Is there anything wrong?

**Comment by rgtjf** [comment]
@faneshion , I can't find this wechat ``CLJ_Keep``.

**Comment by yangliuy** [comment]
@StKlaas  You can search for "CLJ_Keep" when you try to add a new WeChat friend. I just tried. It should work. After you added "CLJ_Keep" as one of your WeChat friends, she will invite you to join the MatchZoo WeChat group. "CLJ_Keep" is one member of the MatchZoo team.

**Comment by shanshanhello** [comment]
me,too. My wechat number is :littleDores. Thank you.

**Comment by wawang250** [comment]
hi, I applied for 'CLJ_Keep', please confirm my request~ thx~

**Comment by thiziri** [comment]
Hi,
I've just sent an invitation (or request) to 'CLJ_Keep', thanks for adding me 'thiziri_belkacem'
Best

**Comment by bwanglzu** [comment]
currently, the wechat group is quiet ``silent'', might be a good idea to communicate via GitHub issues.
