### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#142]
Add contributing.md in our 2.0 version. 

See what is CONTRIBUTING.md and how to write [here](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

**Comment by bwanglzu** [comment]
@aneesh-joshi 's advice :)

**Comment by aneesh-joshi** [comment]
Please checkout this awesome Contributing.md from gensim

https://github.com/RaRe-Technologies/gensim/blob/develop/CONTRIBUTING.md
