### ISSUE TITLE
corpus_preprocessed.txt 里的数据格式是否是(Did,Did_length,word_id)?

### ISSUE THREAD

**Issue by YSZYCF** [faneshion/MatchZoo#146]
我在阅读你的reade.me里面，发现,给出了corpus_preprocessed.txt**: Each line is corresponding to a document. The first column is document id. The second column is the document length, followed by the ids of words in this document.但是我在Preprocess.py文件里，发现
   # Prerpocess corpus file
    preprocessor = Preprocess(min_freq=1)
    dids, docs = preprocessor.run(basedir + 'corpus.txt')
    preprocessor.save_word_dict(basedir + 'word_dict.txt')
    preprocessor.save_words_stats(basedir + 'word_stats.txt')

    fout = open(basedir + 'corpus_preprocessed.txt', 'w')
    for inum, did in enumerate(dids):
        fout.write('%s\t%s\n' % (did, ' '.join(map(str, docs[inum])))
    fout.close()
    print('preprocess finished ...')
似乎basedir + 'corpus_preprocessed.txt',里面并没有the document length,并且尝试阅读Preprocess的源码,docs里面，每一行的第一列似乎也不是the document length.

可以给我一些帮助忙，想知道docs里面每一行的第一列是否是 the document length?

**Comment by bwanglzu** [comment]
We expect you to ask questions in English, so that everyone can understand & help you :)

**Comment by WelcomeLi** [comment]
Each line the fitst column is the QID(query Id) or DiD(document id)，then the second column to the end column is the embedding id respectively. So the length between the second column and the end column is the document length or the query length.

**Comment by changlinzhang** [comment]
To be exact, it is '' doc_id, doc_length, doc_words" in `corpus_preprocessed.txt` while it isnt so in `corpus.txt`.
