### ISSUE TITLE
Getting nan for prediction of arcii in predict.test.wikiqa.txt

### ISSUE THREAD

**Issue by aneesh-joshi** [faneshion/MatchZoo#147]
On running `main.py` with `--phase predict` on arcii,
the file gives nan values for predictions:

Example:
```
Q2241	Q0	D19687	0	nan	ARCII	1
Q2241	Q0	D19686	1	nan	ARCII	0
Q2241	Q0	D19685	2	nan	ARCII	0
Q2241	Q0	D19684	3	nan	ARCII	0
Q2241	Q0	D19683	4	nan	ARCII	0
Q2241	Q0	D19682	5	nan	ARCII	0
Q2242	Q0	D19692	0	nan	ARCII	1
Q2242	Q0	D19693	1	nan	ARCII	0
Q2242	Q0	D19691	2	nan	ARCII	0
Q2242	Q0	D19690	3	nan	ARCII	0
Q2242	Q0	D19689	4	nan	ARCII	0
Q2242	Q0	D19688	5	nan	ARCII	0
Q2243	Q0	D19697	0	nan	ARCII	1
Q2243	Q0	D19698	1	nan	ARCII	0
Q2243	Q0	D19696	2	nan	ARCII	0
```

other predictions however seem to work:
`map=0.382256	ndcg@1=0.198312	ndcg@3=0.293003	ndcg@5=0.416683	ndcg@10=0.502918	ndcg@20=0.513140`

**Comment by aneesh-joshi** [comment]
@faneshion 
I have the latest version.
I am still getting the `nan` value.

Is there a data dependency which I may be missing?

**Comment by bwanglzu** [comment]
I can't reproduce the error, maybe your configuration is incorrect?

**Comment by aneesh-joshi** [comment]
Will check again and let you know soon.

**Comment by bwanglzu** [comment]
thanks
