### ISSUE TITLE
How does MatchZoo choose training pairs

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#148]
Hi,
Since in the issue #132 the model does not reduce the error considerably, I was thinking about the input data, I mean: what's the impact of the order of input data in "relation_train" file or it's managed by MatchZoo? If so, how can I manage the input data to have a better loss minimization? 
Could you please show me how and where does MatchZoo construct its X_train and Y_train (training pairs)?
Thanks again.
@faneshion @yangliuy @bwanglzu

**Comment by faneshion** [comment]
Hi, there is no effect of the order in the relation files. All pairs are constructed with make_pair_static or make_pair_iter. While training, all training samples are randomly sampled from the constructed pairs.

**Comment by faneshion** [comment]
Hi, there is no effect of the order in the relation files. All pairs are constructed with make_pair_static or make_pair_iter function in pair_generator.py. While training, all training samples are randomly sampled from the constructed pairs.

**Comment by thiziri** [comment]
Okay, that's better.  Thanks for your response.
But, in case I need to customize the sampling of training pairs, is there a way to respect some order? I, mean: does MatchZoo provide the possibility to set the order of training pairs?
Thanks again

**Comment by bwanglzu** [comment]
@thiziri Maybe it could be a good one for matchzoo 2.0 :)

Can you clarify a little bit about how would you like to customize training pairs?

**Comment by thiziri** [comment]
@bwanglzu I mean the ordering of reading training pairs:
exp: let {(x1,y1), (x2,y2), (x3,y3), (x4,y4)} training set.
objective: train MatchZoo with (x3,y3) then (x1,y1) then (x4, y4) then (x2, y2)
Is it possible to do something like this with MatchZoo? How?
Thanks again

**Comment by bwanglzu** [comment]
@thiziri If you need some random permutation during training, I'd suggest to look at `main.py`, [Line](https://github.com/faneshion/MatchZoo/blob/93a2999175f99d134efdcb6ca33c9827991a82ec/matchzoo/main.py#L153), change `shuffle=True`.

If you want to artificially change the sequence of input data, I'm not 100% sure whether it's possible.

**Comment by thiziri** [comment]
Okay, thanks a lot.
I've got my answers, you can close this issue.
Thanks again
