### ISSUE TITLE
人已经满了

### ISSUE THREAD

**Issue by ruzwdy** [faneshion/MatchZoo#15]
二维码 人数已经超过100 ，请拉一下  w16402151618

**Comment by faneshion** [comment]
这个是微信号码吗？搜索不到这个w16402151618这个账号~

**Comment by yangliuy** [comment]
@ruzwdy We have applied another wechat number: CLJ_Keep. Any one who want to join the group and add this number.  You can search for "CLJ_Keep" when you try to add a new WeChat friend. After you added "CLJ_Keep" as one of your WeChat friends, she will invite you to join the MatchZoo WeChat group. "CLJ_Keep" is one member of the MatchZoo team.
