### ISSUE TITLE
Hi! a question in "matchpyramid.py"

### ISSUE THREAD

**Issue by RadioSura** [faneshion/MatchZoo#152]
first, THX to your job that make NLP task more easy to build!

I find your "mathpyramid" implement after read your brilliant paper "Text Matching as Image Recognition",  in this paper, you gave three examples as "Indicator Function", "Dot Product", "Cosine", but i have not found your code include such opearators .
could you tell me any details about operators design? 

THX again your job 👍

**Comment by bwanglzu** [comment]
@RadioSura I've assigned the issue to the author, have fun with him :)

**Comment by pl8787** [comment]
matchpyramid.py at line 53

For Dot Product: 

``` python
 cross = Dot(axes=[2, 2], normalize=False)([q_embed, d_embed])
```

For Cosine:

```python
 cross = Dot(axes=[2, 2], normalize=True)([q_embed, d_embed])
```

For Indicator Function:

``` python
def xor_match(x):
            t1 = x[0]
            t2 = x[1]
            t1_shape = t1.get_shape()
            t2_shape = t2.get_shape()
            t1_expand = K.tf.stack([t1] * t2_shape[1], 2)
            t2_expand = K.tf.stack([t2] * t1_shape[1], 1)
            out_bool = K.tf.equal(t1_expand, t2_expand)
            out = K.tf.cast(out_bool, K.tf.float32)
            out = K.tf.expand_dims(out, 3)
            return out
```

**Comment by bwanglzu** [comment]
@RadioSura Contribution is always welcomed, however, we're currently implementing MatchZoo 2.0, current models will be replaced by the new engine. We'll finalize engine design and release tasks in near future, please keep an eye on [project](https://github.com/faneshion/MatchZoo/projects/1) board and issues labeled with `2.0`, thanks again!

I'll close this issue for now, if you have further questions please feel free to re-open it or create a new issue. Best!
