### ISSUE TITLE
Some question about DRMM_TKS 

### ISSUE THREAD

**Issue by WelcomeLi** [faneshion/MatchZoo#158]
whether exixt the paper that detailed introduce the DRMM_TKS ?

**Comment by faneshion** [comment]
In fact, this method incorporated ideas from DRMM and PACRR (2017 A Position-Aware Deep Model for Relevance Matching in Information Retrieval), it has not been published.

**Comment by bwanglzu** [comment]
@WelcomeLi I'll close this issue for now, hope your question has been solved, best!
