### ISSUE TITLE
Drmm_tks

### ISSUE THREAD

**Issue by imsure318** [faneshion/MatchZoo#16]
Is it possible to provide further details on DRMM_TKS (I mean, paper).

**Comment by faneshion** [comment]
Right now, it is our idea to expand DRMM on short text pairs. So, you can refer the paper DRMM to understand the code. It's not much hard.

**Comment by JiafengGuo** [comment]
It is based on DRMM, by replacing the matching histogram by top-k strongest signals for short texts.

**Comment by imsure318** [comment]
@faneshion @JiafengGuo Thanks!
