### ISSUE TITLE
How can I use for chinese corpus?

### ISSUE THREAD

**Issue by caoxu915683474** [faneshion/MatchZoo#163]
Thanks for sharing of this good work! 
These days I 'm doing some work in chinese sentence matching , so how can I easily use your work in chinese project?
I will appreciate it if you can help me with this problems. Thank you !

**Comment by faneshion** [comment]
For Chinese corpus, you can segment the raw text into tokens with space between them. Then, you can do it as we have done in English corpus. You can follow this [script](https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/run_data.sh).
