### ISSUE TITLE
Design DataPack Interface

### ISSUE THREAD

**Issue by pl8787** [faneshion/MatchZoo#175]
![image](https://user-images.githubusercontent.com/1762835/41358774-ae6eb9ce-6f5b-11e8-9d81-0790dfc89e1a.png)

**Comment by bwanglzu** [comment]
The idea is to use `ProcessUnit` as atom element to handle pre-process actions, and **Chain** a  sequence of units based on requirements. Some pseudo code:
```python
class ProcessUnit(object):
    @staticmethod
    @abc.abstractmethod
    def _process(input):
        return

    @abc.abstractmethod
    def fit(self, input):
        return

    @abc.abstractmethod
    def transform(self, input):
        return

    @classmethod
    def fit_transform(cls, input):
        ctx = cls.fit(input)
        rv = cls.transform(input)
        return rv, ctx # rv is return value of transform action, ctx is statistics of fit action.
```

**Comment by bwanglzu** [comment]
To create an `ProcessUnit`, inherit from `ProcessUnit` class. For example, to **tokenize** user input, we create a `TokenizeUnit` class:

```python
class TokenizeUnit(ProcessUnit):

    def _process(input):
        return nltk.word_tokenize(input)

    def fit(self, input):
        return # fit is not needed for tokenization

    def transform(self, input):
        return TokenizeUnit._process(input)
```

**Comment by bwanglzu** [comment]
For user input, we specify a sequence (ordered) of `ProcessUnit`, and add these Units into a `Chian` class:

```python
class Chain(collections.deque):
    """The class chain an ordered sequence of ProcessUnit"""
    pass

processors = Chain(
    TokenizeUnit(),
    PuncRemovalUnit() # Remove punctuation from input.
    DigitRemovalUnit() # Remove digits from input.
    StemmingUnit # Stemming.
    ...
)   
```

**Comment by bwanglzu** [comment]
@aneesh-joshi @thiziri How do you think the idea for MZ 2.0 data pre-processing? (through it will not exposed to users)

**Comment by uduse** [comment]
Just dumping some ideas here:

- `processor = Chain(A, B, C)` is weird. Try something like `processor = Processor(pipeline=[A, B, C])`
- Processing units may have the following structure: 
    ```
                 ProcessingUnit
                   (+ abstract method transform)
                  /                  \
    StatelessUnit            StatefulUnit
                                         (+ attribute ctx)
                                         (+ abstract method fit)
    ``` 
    where things like tokenizers and stemmers are `StatelessUnit` and things like build a vocabulary are `StatefulUnit`. `ctx` only exists in `StatefulUnit` since, well, it's stateful. Also, I discarded method `fit_transform` because 1. it belongs to a comprehensive API, but we only need barebones, and 2. I putted `ctx` in an attribute so `fit_transform` only saves one line of code, but does `fit_transform` = `fit` + `transform` ? At least it should, but we could avoid that confusion all together.
- `class Chain(collections.deque)`? it does much less than a `deque`, so it shouldn't be a `deque`. Delegates that to a simple list suffices.
- or, we can use `dask.delayed` or `bonobo` or something similar to construct a computation graph instead of simply chaining them. This leaves ample space for performance optimization later on.

**Comment by bwanglzu** [comment]
@uduse yes these are just some pseudo scripts in my mind, we can defined it lately.

**Comment by uduse** [comment]
@bwanglzu I changed the class name in (1) as well. I mean, `preprocessor` should be a `Preprocessor`, right?

**Comment by bwanglzu** [comment]
@uduse yes correct.

**Comment by bwanglzu** [comment]
@uduse @faneshion @pl8787 An example of Dask processor (not fully tested):

```python
"""Dask adapter. Process pair-wise list of input in parrllel."""

from dask.multiprocessing import get

from preprocessors import TokenizeUnit, DigitRemovalUnit, PuncRemovalUnit

class DaskAdapter(object):
    """"""

    def __init__(self, text_left, text_right, process_units):
        self.text_left = text_left
        self.text_right = text_right
        # Create process units, define a sequence of normalize steps.
        if not process_units:
            raise ValueError("")
        self.process_units = process_units
    
    def dsk(self):
        """Build dask computational graph."""
        graph = {}
        # Create graph input layer.
        unit = self.process_units[0]
        key = str(type(unit).__name__)
        graph['-'.join([key, 'left'])] = (unit, self.text_left)
        graph['-'.join([key, 'right'])] = (unit, self.text_right)
        self.process_units.pop(0)
        # Create rest layers.
        for unit in self.process_units:
            prev_key_left = '-'.join([key, 'left'])
            prev_key_right = '-'.join([key, 'right'])
            key = str(type(unit).__name__)
            graph['-'.join([key, 'left'])] = (unit, prev_key_left)
            graph['-'.join([key, 'right'])] = (unit, prev_key_right)
        return graph
    
    def get_last_unit(self):
        """Get last processing unit."""
        return self.process_units[-1]
    
    def fit_transform(self):
        """Execute computational graph."""
        last_unit_name = str(type(self.get_last_unit()).__name__)
        graph = self.dsk()
        rv_left = get(graph, '-'.join([last_unit_name, 'left']))
        rv_right = get(graph, '-'.join([last_unit_name, 'right']))
        return [rv_left, rv_right]

process_units = [TokenizeUnit(), DigitRemovalUnit(), PuncRemovalUnit()]
da = DaskAdapter("This is Query!", "This is Document 1!", process_units)
graph = da.dsk()
print(graph)
print(da.fit_transform())
```

**Comment by bwanglzu** [comment]
@uduse how to use `@dask.delayed` on a sequence of operations?

**Comment by uduse** [comment]
@bwanglzu [http://dask.pydata.org/en/latest/delayed.html](see the docs), it's quite independent from other dask stuff, so it can be used individually.
