### ISSUE TITLE
Caregorize ProcessUnit

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#176]
If everyone agree the way we design for our first version of `pre-processor` (see #175 ), we need to design the (potentially nedded) `ProcessUnits`.

Roughly, we have three type of `ProcessUnit`:

1. The input data is **raw** text, the `ProcesUnit` should be used for segmentation/tokenization. 

2. `ProcessUnit` designed for text normalization, such as stemming, stop words removal, white space removal etc..

3. `ProcessUnit` designed for post-normalization activities, such as build vocabulary (need discuss)

**Comment by wqh17101** [comment]
We need to provide a Unit which can filter some words from users' customized word list for them

**Comment by uduse** [comment]
@wqh17101 a unit that filter words is easy enough to write your own, so I don't think it has to be in matchzoo.
