### ISSUE TITLE
ARC-II的实现问题

### ISSUE THREAD

**Issue by rgtjf** [faneshion/MatchZoo#18]
关于ARC-II的实现，有一个问题期待解决一下：
1. 在实现ARC-II时，在做``Flatten``这步的时候，由于句子有padding, 最后会出现很多0项，之后再在后面加全连接层，会出现很多0。我当时实验下来效果不好，我想问一下你们是怎么解决的，在一开始padding的时候补的句子中的词吗？谢谢
https://github.com/faneshion/MatchZoo/blob/4431352bf62459f6b19c375690ff39173f20197f/matchzoo/models/arcii.py#L77-L84

**Comment by faneshion** [comment]
我们当前的实验中是直接flatten的，padding的时候也是使用的0， 你可以尝试将maxpooling2D改成dynamicMaxPooling试试~

**Comment by rgtjf** [comment]
多谢解答~
ARCII -> MV-LSTM -> MatchPyramid， 感觉这一系列都很赞！
1.  flatten出现稀疏化的问题，MV-LSTM中的dynamicMaxPooling很好的解决了
2.  直接取最大的K个会不会丢失位置信息，MatchPyramid很好的解决了
