### ISSUE TITLE
import problem: No module named resource

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#182]
i use pip install matchzoo to install.and when i import matchzoo,i met a problem
![default](https://user-images.githubusercontent.com/26429138/41580188-8a3e6a2a-73cc-11e8-92be-296eedf126d8.png)

**Comment by bwanglzu** [comment]
Please refer to #30.

**Comment by bwanglzu** [comment]
@faneshion @ususe we need to remove ‘resource’ package or at least write a more robust function.

**Comment by bwanglzu** [comment]
@wqh17101 thanks for reporting this issue, I've created a pull request to handle it.

**Comment by bwanglzu** [comment]
We’ve updated the code, please use git pull, and reinstall the required libraries
