### ISSUE TITLE
Chinese word dict Problem

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#185]
Hi,when i use test_preparation_for_classify to generate my data from a Chinese Sample.
The format is like 1/t你好 你好/t大家好 大家好.label/tseq1/tseq2.The seq1 and seq2 are the results after word segmentation.Every seq is like word1 word2 word3. 
And then i run test_preparation_for_classify with 
![image](https://user-images.githubusercontent.com/26429138/41633793-21d32f78-7473-11e8-8200-af9b0ebee299.png)
then i got a word_dict which is like that
![image](https://user-images.githubusercontent.com/26429138/41633827-588d6484-7473-11e8-8f3a-8088e87f8079.png)
it is based on letters not words,i want to know how i can get the word based dict

**Comment by wqh17101** [comment]
all right ,i modified the preprocess.py script ,i fixed.
Maybe you need more detailed document about how to use this tool to preprocess chinese documents for the users and a detailed tutorial about this tool.
Also , the paths in main.py and the configs are not flexible.It will cause many problems by relative path and absolute path. 
It is an amazing toolkit.I hope it can get better for users.i wonder whether i can make some contributions to this repo.

**Comment by faneshion** [comment]
You can set 'word_seg_config' as True in the `Preprocess`. By the way, you can look into the `Preprocess` class for more configurations.

**Comment by faneshion** [comment]
@wqh17101 We are working on the MatchZoo 2.0. In this version, we will make the data processing stage more clear and simple. Hope you can join us to develop the MatchZoo 2.0.

**Comment by wqh17101** [comment]
@faneshion That is cool. it is my pleasure to join you. So what should i do and how to communicate with you

**Comment by bwanglzu** [comment]
@wqh17101 drop me an email of your wechat id: kingbolanda@live.com

**Comment by logicmd** [comment]
Hi Folks,

Could you help elaborate where to find test_preparation_for_classify.sh? 
Thanks!
