### ISSUE TITLE
Undefined Var

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#187]
in MatchZoo/matchzoo/inputs/point_generator.py line 290，there is a undefined var 'randomly' which cause NameError: global name 'randomly' is not defined

**Comment by wqh17101** [comment]
And i set it False,it can work now.
i try to run anmm.it seems that everything is ok at the beginning.
![image](https://user-images.githubusercontent.com/26429138/41696752-4ceee050-7548-11e8-9eb1-47d15c1758e1.png)
But some epochs latter,it didnt work.
![image](https://user-images.githubusercontent.com/26429138/41696792-7d63b148-7548-11e8-9523-23ae1cf41aa0.png)

**Comment by wqh17101** [comment]
every model which uses DRMM_PointGenerator has this problem.

**Comment by faneshion** [comment]
It's really a bug in data generation. Thanks for your help.  The `DRMM_PointGenerator` is used under classification task (i.e., QuoraQP) by DRMM and ANMM. I will fixed it right now.

**Comment by wqh17101** [comment]
I will try.
