### ISSUE TITLE
How to use the model i trained to predict?

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#188]
I have trained some models .
Now, i have a new dataset to predict.
So, What should i do? Just run the preparation as what i did when i trained. Or i should add the new dataset to the my old dataset,and then run the preparation together.

**Comment by wqh17101** [comment]
Because if i just run the preparation as what i did when i trained, the new word_dict.txt is different from  the old one. Such as in the old one , 0 represents hello ,but in the new one, 0 represents you . It is really different .Then i use the old model to predict. I think it will not be a good result, will it?

**Comment by Genie-Liu** [comment]
I try to combine the train and test dataset together. And then split myself.
