### ISSUE TITLE
Some thing may make users confused

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#190]
In the utils/rank_io.py , I mention two functions, the one is read_word_dict which can return word_dict(no:word) and iword_dict(word:no). Another is read_data. 
If sourcefile's format is like T1 len 1 2 3 such as corpus_preprocessed in the example.
you used read_data(source_file,word_dict=None)
![image](https://user-images.githubusercontent.com/26429138/41722589-9817f80c-759b-11e8-8950-99aa8c574912.png)
data={'T1':[1,2,3]}
Let's suppose that i have a word_dict.txt which is like you provided in the data/toy_example .So i use read_word_dict to get a word_dict(no:word). Then i use read_data(source_file,word_dict=word_dict).
![image](https://user-images.githubusercontent.com/26429138/41722862-3d24b7fe-759c-11e8-8ae7-91a6b799f6b8.png)
you will get a  wrong result.
To get the right result like data={'T1':[1,2,3]}.
The sourcefile's format should be T1 len word1 word2 word3.And word_dict should be like word:no,not no:word which is the format of word_dict defined in the read_word_dict.
i think you should change def read_data(filename, word_dict = None) to def read_data(filename, iword_dict = None) or make some comments here

**Comment by rgtjf** [comment]
@wqh17101 Do you mean it is better to use the `iword_dict` instead of `word_dict` in the function `read_data`?

**Comment by wqh17101** [comment]
Yes @rgtjf 
if you want to get data={'T1':[1,2,3]} as  the final result no matter what your sourcefile'format is like(T1 len 1 2 3 or T1 len word1 word2 word3 ).

**Comment by bwanglzu** [comment]
let's focus on code quality in 2.0 first.
