### ISSUE TITLE
explicit relative and absolute import should be a better choice

### ISSUE THREAD

**Issue by stanpcf** [faneshion/MatchZoo#198]
Hi, I had read some code in this repo which I find that relative and absolute import is implicit. which will  cause module will be hided in sys.path and cause more bugs. going to code declaration in some ide also difficult. 
example in [matchzoo/models/matchpyramid.py line 12](https://github.com/faneshion/MatchZoo/blob/50422a5bc973d27b8c507122aa3f41e633366893/matchzoo/models/matchpyramid.py#L12) it's better to write `from ..utils.utility import *` instead of `from utils.utility import *`. The later code will caused a bug in my computer, because there is another `utils` module in my `sys.path`.
using relative import will cause run `python matchzoo/main.py --phase train --model_file examples/toy_example/config/arci_ranking.config` failure. However runing `python -m matchzoo.main --phase train --model_file examples/toy_example/config/arci_ranking.config` can perfectly solve this problem. 

some awesome code such as [tensorflow/nmt](https://github.com/tensorflow/nmt#hands-on--building-an-attention-based-nmt-model) use this code style. 
- relative import all module for our pkg and absolute import all module in sys.path.
- using `python -m ` to run the code

`python -m ` style can also be perfect for module which is installed in site-package. such as we can use `python -m http.server` in py3 or `python -m SimpleHTTPServer` in py2 to run a simple httpserver using standard library `http` in py3 or `SimpleHTTPServer` in py2. and the `http/sever.py` can also be imported in our code. While to run `python {path-to-http.server}/http/server.py` is cumbersome

**Comment by bwanglzu** [comment]
Hi @stanpcf, thanks for your advice.

As you might noticed that we’re building MatchZoo 2.0 from scratch (issues labeled with 2.0).  In 2.0 we’ll unify import strategy.

We’re not going to refactor master branch since it’s not our priority.

Thanks again, best!
