### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by DavidGOrtega** [faneshion/MatchZoo#2]
Hi,

I have tried to setup the project as described however the data is missing. 
Looking at the models config file I could state that are referencing unavailable folders. If you try to setup the project in a vanilla enviroment will find something like this.

```
IOError: [Errno 2] No such file or directory: u'../data/mq2007/embed.idf'
```

**Comment by faneshion** [comment]
Hi, the mq2007 dataset is a too large for this github project. For simplification, I will make a example data file later.

**Comment by DavidGOrtega** [comment]
Hi, thanks for the reply. I have read the paper already and I could not get how to prepare the data using my query/doc pairs. Is there any function in the code that would build it?

**Comment by faneshion** [comment]
Yeah,  the preparation file is in matchzoo/inputs/prepation.py.  You can transfer the query/doc pairs into two/three files, including corpus file and relation file. Then you can pass the corpus file into preprocess.py to filter rare words. You can check this process in the examples/test_preparation.py.

**Comment by super-zhangchao** [comment]
Hi, '../data/mq2007' is empty, Can you upload a copy? Thx

**Comment by faneshion** [comment]
@super-zhangchao The MQ2007 dataset is too large to upload, you can follow the example file to construct your own model~ Welcome to any other question~

**Comment by shellbacksq** [comment]
Hi, I found MQ2007 dataset there [http://www.bigdatalab.ac.cn/benchmark/bm/dd?data=MQ2007](url). it like:
`====================================================
  Folds     Training set   Validation set   Test set

  Fold1     {S1,S2,S3}          S4              S5 

  Fold2     {S2,S3,S4}          S5              S1 

  Fold3     {S3,S4,S5}          S1              S2 

  Fold4     {S4,S5,S1}          S2              S3 

  Fold5     {S5,S1,S2}          S3              S4 
==================================================`
How can i convert it to satisfy your model?

**Comment by faneshion** [comment]
In fact, this dataset can not be used for MatchZoo due the missing of document contents. The original document contents of MQ2007 are from GOV2 corpus. You can apply it from NIST(http://trec.nist.gov/).

**Comment by loveJasmine** [comment]
how to make it run !!

**Comment by faneshion** [comment]
@loveJasmine It's my fault that the drmm.config is on the MQ2007 dataset whose corpus is not public due to the TREC policy. We update the README, you can now run the command  based on the example dataset in data/example/ranking.

**Comment by yangliuy** [comment]
@loveJasmine  You can check the format of input data in https://github.com/faneshion/MatchZoo/blob/master/data/example/readme.md to transfer your data in such format. Then it is easy to run MatchZoo with your own data. You can also use the Python scripts in MatchZoo/examples/ for this data format transformation.

**Comment by loveJasmine** [comment]
thanks @yangliuy @faneshion
