### ISSUE TITLE
I cannot successfully install MatchZoo by running "python setup.py install"

### ISSUE THREAD

**Issue by LayneIns** [faneshion/MatchZoo#20]
It just went wrong when installing tensorflow and related packages, saying that "no local packages or working download links found for tensorflow"
Are you sure the command is bug-freed?

**Comment by faneshion** [comment]
We have tested the installing by running "python setup.py install --user". Can you show the detail of the errors? By the way, you can install the dependencies by yourself, then, MatchZoo can work as normal.

**Comment by WillsNew** [comment]
```
Processing dependencies for MatchZoo==0.2.0
Searching for tensorflow-tensorboard<0.2.0,>=0.1.0
Reading https://pypi.python.org/simple/tensorflow-tensorboard/
No local packages or working download links found for tensorflow-tensorboard<0.2.0,>=0.1.0
error: Could not find suitable distribution for Requirement.parse('tensorflow-tensorboard<0.2.0,>=0.1.0')
```


This is the error

**Comment by MacXing** [comment]
Download TensorFlow first
