### ISSUE TITLE
Cross-referencing Python objects

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#208]
Update cross-reference python objects in docstring for documentation.

To resolve:

```python
docstring of matchzoo.engine.base_model.BaseModel.guess_and_fill_missing_params:1: WARNING: Unknown interpreted text role "attribute".
```
Use
```python
"""
:attr:
"""
```

The possible objects are listed [here](http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing-python-objects)

**Comment by uduse** [comment]
`:attribute:` is also in the list, but somehow not supported 😞

**Comment by bwanglzu** [comment]
Anyway, let’s change in our side
