### ISSUE TITLE
Not a big deal, but make a little confused while reading the code

### ISSUE THREAD

**Issue by Genie-Liu** [faneshion/MatchZoo#222]
In the file /data/QuoraQP/prepare_mz_data.py  line89-91
https://github.com/faneshion/MatchZoo/blob/50422a5bc973d27b8c507122aa3f41e633366893/data/QuoraQP/prepare_mz_data.py#L89-L91

I think tric and tri_id should swap, and then it makes sense. Although the original code works the same. But for reading code, it makes a little confused.

**Comment by bwanglzu** [comment]
Hi, it’s true that the current version of MatchZoo source code is a bit hard to read, but we’re not going to refactor it. 

We’re working hard to deliver MatchZoo 2.0. Check out 2.0 branch for more information.
