### ISSUE TITLE
I met errors when I run "python example/toy_example/test_preparation_for_classification.py"

### ISSUE THREAD

**Issue by WillsNew** [faneshion/MatchZoo#23]
[kkk@MatchZoo]$ python examples/toy_example/test_preparation_for_classify.py 
Traceback (most recent call last):
  File "examples/toy_example/test_preparation_for_classify.py", line 7, in <module>
    from preparation import *
ImportError: No module named preparation

Obviously, you said I should run "python examples/testpreparationforclassification.py". This is a mistake, right? I wonder why the usage is different from the descriptions in your readme...
And are you really sure that you can run the code on your server?

**Comment by uduse** [comment]
I am having the same problem. Despite the problem itself, I think the team barely knows software engineering practices. Given that the project has really high quality content now, I am confident that all they need to bring this project to a tier one open source project is either a single person knows these practices, or the team being open to such changes.

**Comment by yangliuy** [comment]
Thank you for the feedback! We will fix this bug soon. Meanwhile, if you have any more concrete suggestions/resources on how to improve the quality of development/testing phases of this project, feel free to add here.

**Comment by uduse** [comment]
@yangliuy Sure. I am still reading the source code. I will submit an issue that discusses the design of the project once I understand the guts of the project. I sincerely believe this project has a bright future. Thank you all for your effort on doing this.
