### ISSUE TITLE
when the data is very large, the training progress is too slow

### ISSUE THREAD

**Issue by kinglai** [faneshion/MatchZoo#233]
My training data is very large ,the training progress is very slow.
And I use the "use_iter": true.

First I think it's because my much more data is used during each iter, but when I chech the code, I find it just use batch_per_iter batchs per iter, and each batch just use batch_size samples, that is, the training data during each iter is the same.

So why the training time per iter is much more large when there is much more training data?
 
ps, I use PairGenerator.

**Comment by bwanglzu** [comment]
reference to #40
