### ISSUE TITLE
Bad docstring

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#235]
https://github.com/faneshion/MatchZoo/blob/2.0/matchzoo/preprocessor/process_units.py
![default](https://user-images.githubusercontent.com/26429138/42611374-623b38e2-85c8-11e8-80e0-6f7f0614c56b.png)
a small mistake

**Comment by uduse** [comment]
If it's a simple fix like this you can directly PR.

**Comment by uduse** [comment]
Done. 61ad48273518de3d40fca9b331f4798ac8995cda

**Comment by wqh17101** [comment]
all right
