### ISSUE TITLE
how to use my own dataset to predicted a sentence's answers with DRMM model 

### ISSUE THREAD

**Issue by Masterchenyong** [faneshion/MatchZoo#236]
I had research  the drmm algorithm and it's code ,The input of model is query and Histogram from qurey and document  Whether it's training or predict .if i want to find a  new queyy's best answer ,should
i have to build  Histogram use new query with all document  ?   what should i do?  i had  be troubled for a long time. thanks!

**Comment by faneshion** [comment]
Yeah, the input of DRMM is the matching histogram. For testing, you should build matching histogram for each query-document pair! In fact, you can also design a transformation function to generator matching histogram automatically, here is the [sample code](!https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/gen_hist4drmm.py).

**Comment by faneshion** [comment]
Yeah, the input of DRMM is the matching histogram. For testing, you should build matching histogram for each query-document pair! In fact, you can also design a transformation function to generator matching histogram automatically, here is the [sample code]!(https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/gen_hist4drmm.py).

**Comment by faneshion** [comment]
Yeah, the input of DRMM is the matching histogram. For testing, you should build matching histogram for each query-document pair! In fact, you can also design a transformation function to generator matching histogram automatically, here is the [sample code](https://github.com/faneshion/MatchZoo/blob/master/data/WikiQA/gen_hist4drmm.py).

**Comment by Masterchenyong** [comment]
I have tried this method，but that is need too time  to matching histogram .

**Comment by bwanglzu** [comment]
@Masterchenyong do you mean need too much time?

**Comment by datistiquo** [comment]
@faneshion @bwanglzu The sample code link does not work anymore . Where can I find this?

**Comment by Vineet-Sharma29** [comment]
Any idea how to train a model like on custom dataset like a large corpus of text files? Is there a way so that I can build my model on some of own dataset?
