### ISSUE TITLE
能否提供一个更换数据集的操作文档

### ISSUE THREAD

**Issue by danner1** [faneshion/MatchZoo#25]
能否提供一个用matchzoo模型更换数据集进行实验的操作文档，main.py看的有点晕

**Comment by mattzheng** [comment]
同感，研究了一天，才发现.config文件里面，有这么多东西....
结构写的非常棒，而且适用各类model，就是需要稍微解释一下~

**Comment by yangliuy** [comment]
Config文件的解释可以查看 https://github.com/faneshion/MatchZoo/blob/master/matchzoo/models/README

**Comment by faneshion** [comment]
@danner1 更换数据集的说明我们正在准备，另外，你可以参考example里面的toy_example路径下的 geneate_ranking_data.sh, 这个脚本提供从sample.txt生成matchzoo的格式data的全部操作~
