### ISSUE TITLE
pad word index

### ISSUE THREAD

**Issue by dingran** [faneshion/MatchZoo#254]
https://github.com/faneshion/MatchZoo/blob/5bd90d999fd47558be3154eb5bbc3dcd41a834b3/matchzoo/main.py#L67

Padding like this would use last word in vocab to pad, in the wikiqa example, it uses the word 'brisket' to pad...

I think it should be
` _PAD_ = share_input_conf['vocab_size'] `

**Comment by bwanglzu** [comment]
Hi @dingran thanks for your message! We’ll look into this and get back to you soon.

**Comment by faneshion** [comment]
Yeah, this is really a bug if the `vocab_size` is set equal to the number of words in dict file. The easiest solution to this is to set the `vocab_size` as the number of words plus one. Though, it is not an elegant solution. We will fixed this.

**Comment by faneshion** [comment]
Yeah, this is really a bug if the vocab_size is set equal to the number of words in dict file. The easiest solution to this is to set the vocab_size as the number of words plus one. Though, it is not an elegant solution. We will fix this.

**Comment by faneshion** [comment]
Yeah, this is really a bug if the `vocab_size` is set equal to the number of words in dict file. The easiest solution to this is to set the `vocab_size` as the number of words plus one. Though, it is not an elegant solution. We will fix this.
