### ISSUE TITLE
running "python setup.py install" failed 

### ISSUE THREAD

**Issue by lbridge** [faneshion/MatchZoo#26]
[ 8/11] Cythonizing /tmp/easy_install-gyR2M6/h5py-2.7.1/temp/easy_install-sqsKKi/Cython-0.27.3/Cython/Plex/Actions.py
[ 9/11] Cythonizing /tmp/easy_install-gyR2M6/h5py-2.7.1/temp/easy_install-sqsKKi/Cython-0.27.3/Cython/Plex/Scanners.py
[10/11] Cythonizing /tmp/easy_install-gyR2M6/h5py-2.7.1/temp/easy_install-sqsKKi/Cython-0.27.3/Cython/Runtime/refnanny.pyx
[11/11] Cythonizing /tmp/easy_install-gyR2M6/h5py-2.7.1/temp/easy_install-sqsKKi/Cython-0.27.3/Cython/Tempita/_tempita.py
warning: no files found matching '2to3-fixers.txt'
warning: no files found matching 'Doc/*'
warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '*.pxd' under directory 'Cython/Utility'
/tmp/easy_install-gyR2M6/h5py-2.7.1/temp/easy_install-sqsKKi/Cython-0.27.3/Cython/Plex/Scanners.c:19:20: fatal e
rror: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

[root@hadoop208 MatchZoo]# uname -a
Linux hadoop208 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@hadoop208 MatchZoo]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

[root@hadoop208 MatchZoo]# cat /proc/version 
Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017

**Comment by faneshion** [comment]
It seems that the error occurs while installing h5py. This may connect to you platform or environment.  I have no better ideas. You can try to install it from source?

**Comment by lbridge** [comment]
Thanks, the problem is solved

sudo pip install h5py
