### ISSUE TITLE
The problems caused by relative path

### ISSUE THREAD

**Issue by snowcement** [faneshion/MatchZoo#285]
all the modules' or files' path in the codes are all using "relative path". When debugging the module, relative path always result in the error , i.e. FileNotFoundError: [Errno 2] No such file.... Does any one know how to solve this problem? thanks a lot!!!

**Comment by bwanglzu** [comment]
are you using *nix?

**Comment by snowcement** [comment]
Yes，the codes are on linux, and I'm using Pycharm for remote debugging on Windows. Modules' relative path would not cause problem but files' path in .config file may result in the error. By modifying the path into absolute path will be ok

**Comment by bwanglzu** [comment]
try to do this:
```shell
cd MatchZoo
pwd
>>> copy your MatchZoo path
export PYTHONPATH=$PYTHONPATH:PASTE-YOUR-MATCHZOO-PATH
```
