### ISSUE TITLE
A question about the manner of input data to model.fit_generator()

### ISSUE THREAD

**Issue by Star-in-Sky** [faneshion/MatchZoo#289]
I find that input data is sent to model by outside circulation iteration. Seeing the follow plot.

![image](https://user-images.githubusercontent.com/9433558/44146408-f68c3d3e-a0c1-11e8-9abe-d0c198ae4565.png)

I am feeling uncertain why do it and I change it to this(because I want to use tensorboard by callback function).
![image](https://user-images.githubusercontent.com/9433558/44146477-49af5492-a0c2-11e8-9c27-d132686a435a.png)

I just use ``model.fit_generator()`` to handel data and train. However, it raises a exception that is caused by ``validation_data``。
![2018-08-15 19-46-50](https://user-images.githubusercontent.com/9433558/44146859-201275fe-a0c4-11e8-8067-c0f4efc1d4dc.png)
I trace it into keras inner cores and find it occurs when model starts to run ``evaluate_generator()``。In the function evaluate_generator()，eval data generator is empty and lead to a exception at a epoch! However, it is strange and confuses me why the exception does not occur in the start epoch。I trace code and think it may be a bugger of Keras，is it true?
Additional, whether this is the reason that you make a outside iteration to train model。

大佬们好，我发现代码一开始是在外部循环迭代输入数据进入模型训练，我很奇怪并且我想在fit_generator()中调用回调函数，所以我自己手动改了代码，如图2，但是这个产生了一个异常，经过追溯，我发现是model在训练的时候，在一个epoch结束之后调用验证集跑的时候，验证集数据在keras内部代码通过一个队列调用的时候，是空的导致的异常，但是很奇怪的是，这个问题不是一开始的epoch就发生的，而是在epoch好多次之后的某一次epoch，出现了这个异常，我很奇怪，追溯代码，感觉好像是keras的bug，不知道对不对，另外我想一开始的数据处理，是不是为了解决这个问题？求指教～谢谢～

**Comment by Star-in-Sky** [comment]
I have find that the newest Keras has changed the relative codes. This can prove this is a keras bug! However, the first exception still occur. This really confuse me. The exception is the eval data is sent to model by yield, the next yield has no data. Logically speaking, the data should be sent into model by keeping data in continuous cycles. The train data can do it (loop into model, I have verified it!). The manners of dealing train and eval data are same. Why train data is sucessly sent model by looping, the eval data failed?

我这边发现，最新的keras已经修改了代码。现在处理训练数据和验证集数据的方式一样（原来就一样，只不过是一个队列重复创建的过程），但是现在还是出现问题，举例：
> 训练数据 1000， 验证数据 100，batch_size: 20，训练数据step: 1000, 验证数据step:6
现在，训练数据在一个epoch中要循环取20的batch一共1000次，训练数据可以，因为数据取完能重头接着取，而验证集需要取20的batch一共6次，当循环第6次，前5次已经取了 5 x 20 =100的数据，取第6次就认为empty，没有数据了，产生了异常! 这个真的非常奇怪！！！

**Comment by bwanglzu** [comment]
Because there are bugs in the generators.

**Comment by Star-in-Sky** [comment]
Now，I have solve it! In fact, my problem is not only caused by Keras bug but also the ``PointGenerator``。The newset Keras has solved bug. Now, I change the ``PointGenerator`` to run my code.
![](https://user-images.githubusercontent.com/9433558/44146477-49af5492-a0c2-11e8-9c27-d132686a435a.png)

The following plot is my manner sloving my question! I add Line42 ~43. Train data is selected by random manner, eval data is selected one by one. `` self.point`` only controls eval data and when ``self.point==total_rel_num``, it returns None and raises a exception.(Line 44 ~45)


![image](https://user-images.githubusercontent.com/9433558/44204518-8510e780-a185-11e8-9f41-1556601acab0.png)

**Comment by bwanglzu** [comment]
@Star-in-Sky can you send a PR to MatchZoo to resolve the issue?

**Comment by Star-in-Sky** [comment]
@bwanglzu ，What is the meaning of PR? Commit a change to MatchZoo?

**Comment by bwanglzu** [comment]
@Star-in-Sky Exactly, would you like to send a pull request to resolve the bug?

**Comment by Star-in-Sky** [comment]
@bwanglzu This problem only occurs when I change the main.py like following plot. If I commit it to MatchZoo, I must change main.py like the following plot. Now, I willing commit it to MatchZoo today!
![](https://user-images.githubusercontent.com/9433558/44146477-49af5492-a0c2-11e8-9c27-d132686a435a.png)

**Comment by bwanglzu** [comment]
@Star-in-Sky Which line? We have to remove the callbacks.

**Comment by Star-in-Sky** [comment]
@bwanglzu 
orginal main.py  Line 145~ 181 change to the following plot. 
![](https://user-images.githubusercontent.com/9433558/44146477-49af5492-a0c2-11e8-9c27-d132686a435a.png)
You have to remove the callbacks, I don't konw why. I just want to use callback to get tensorboard info. Now, you need I to commit a pull request?

**Comment by bwanglzu** [comment]
你提到:
> 总之，现在的问题是pointgenerator导致的，训练数据的输入不收self.point 控制，self.point 在训练的时候一直是0， 训练数据是随机抽取。验证集数据是按顺序读取，当self.point自加1到和验证集数据相等的时候，返回了一个None, 我现在修该代码，验证集数据仍然按序读入，当读完之后，我手动将self.point置0，这样验证集数据又从0开始读取。

所以bug是在`PointGenerator`对吗？我以为你修复了`PointGenerator`的bug，而不是在`main.py`里写一个workaround。

**Comment by Star-in-Sky** [comment]
@bwanglzu   我想知道，为什么``main.py`` 中间的模型训练要写成 Line: 145 ~ 181 那样？ 外面迭代循环取数据，塞入模型中训练。这个方式很奇怪？不符合常规～

**Comment by bwanglzu** [comment]
@Star-in-Sky  喔，我以为你直接修复了`PointGenerator`的bug。说实话现在这个版本我也是一脸懵逼..

**Comment by Star-in-Sky** [comment]
@bwanglzu 我现在不是清楚原来你们的``PointGenerator``中的bug现象是什么，我记得之前有一次我有提过一个bug，当时也是``PointGenerator``的问题，然后被解决了，我中间有段时间没关注过这个。 我这几天在用这个的时候，觉得这个``main.py``很奇怪，我就自己改掉了，然后产生了这个bug，然后一开始的确是keras内部也有bug, 不过它最新版本改了代码，后来问题没解决，我仔细追述才发现``PointGenerator``中在我修改的``main.py``情况下，有这么个问题。
不过说真的，应该改成我现在的这个样子，模型训练外部取数据实在太奇怪了，**回调函数**都没法往里面写。另外，您之前说，你们准备不用回调函数，为什么？

**Comment by bwanglzu** [comment]
并不是不准备用回调，只是如果你要PR的话还是跟原来尽可能保持一致。
现在的版本有点旧，我们计划全部推到重新弄了，新版本的MatchZoo框架已经搭好了，我们计划在两个月内（大概）推出新的版本，所以没有精力找到，修复这个bug。

**Comment by Star-in-Sky** [comment]
@bwanglzu 好的，明白了～原来的跑跑没问题，我就不PR了，我自己本地改成这样运行，满足我自己现在的需求～

**Comment by bwanglzu** [comment]
@Star-in-Sky ok，感谢！
