### ISSUE TITLE
Is it not right for "embed_path" in examples/wikiqa/config/drmm_wikiqa.config???

### ISSUE THREAD

**Issue by nanzhao** [faneshion/MatchZoo#29]
When I see the configuration file in examples/wikiqa/config/drmm_wikiqa.config and find this:

"embed_size": 300,
"embed_path": "./data/WikiQA/embed.idf",

this file "embed.idf" is generated from "cat word_stats.txt | cut -d ' ' -f 1,4 > embed.idf". And its content like this:
0 4.013749
1 4.035216
2 5.650094
3 8.964280

So is it a bug for configuration for "embed_path"?

**Comment by faneshion** [comment]
You can take embed.idf as an word features, which shares the same format with embed file. The first column is the word id, and what follows are the feature values.
