### ISSUE TITLE
Negative Sampling

### ISSUE THREAD

**Issue by ArthurCamara** [faneshion/MatchZoo#294]
A quick question, that I couldn´t find the answer. Is there a negative sampling parameter in version 0.2? I do realize that it will be implemented on 2.0, (by issue https://github.com/faneshion/MatchZoo/issues/266).

Is there something similar for 0.2? Or should I manually generate these?

**Comment by bwanglzu** [comment]
Hi, I guess the answer is no, see #177. We’ll try to deliver 2.0 asap!
