### ISSUE TITLE
Unable to find test_preparation_for_classify.sh

### ISSUE THREAD

**Issue by logicmd** [faneshion/MatchZoo#296]
Hi Folks,

I found in the document https://github.com/faneshion/MatchZoo/tree/master/data/toy_example saying there is 
- MatchZoo/examples/test_preparation_for_classify.py for classification 
- MatchZoo/examples/test_preparation_for_ranking.py for ranking

I am wondering where to find them.

Thanks!

**Comment by faneshion** [comment]
These two script are in ['MatchZoo/examples/toy_example'](https://github.com/faneshion/MatchZoo/blob/master/examples/toy_example/test_preparation_for_classify.py).

**Comment by logicmd** [comment]
Thank you for the reply! I might have missed before.
