### ISSUE TITLE
SparseFullyConnectedLayer Missing

### ISSUE THREAD

**Issue by Alchemist75** [faneshion/MatchZoo#3]
Hi, I'm trying to set up DSSM, but in dssm.py SparseFullyConnectedLayer is used and the definition is missing. Can you upload the relevant files? Thanks!

**Comment by faneshion** [comment]
@Alchemist75 It's my fault that I missed this file. There're still some problem in sparse version of DSSM.  I fixed this problem by replacing the sparse version with dense version. This is not an elegant solution. We are working on it ~

**Comment by Alchemist75** [comment]
Thanks~ I recognized the addition, but in dssm.py the layer's still not used(it's still the dense version). Can I use it now or is it still under construction?

**Comment by faneshion** [comment]
Yeah, the dense version is now ready, you can use it. As for the sparse version, there are some minor problems, we are running on it~

**Comment by Alchemist75** [comment]
Thanks!
