### ISSUE TITLE
ImportError: No module named 'resource'

### ISSUE THREAD

**Issue by shanshanhello** [faneshion/MatchZoo#30]
When  i use "python matchzoo/main.py --phase train --model_file examples/toy_example/config/arci_ranking.config" to test, however，The following problems arise ：

D:\tool\MatchZoo-master\matchzoo>python main.py --phase train --model_file ./moels/arci_ranking.config
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "D:\tool\MatchZoo-master\matchzoo\utils\__init__.py", line 9, in <module  from .utility import import_class
  File "D:\tool\MatchZoo-master\matchzoo\utils\utility.py", line 5, in <module>
    import resource
ImportError: No module named 'resource'

what can i do?

**Comment by uduse** [comment]
`resource` is a Python built-in package, but it's only for Unix systems. See [here](https://docs.python.org/2/library/unix.html). I can tell you're using Windows from your output paths. So it's most likely the problem.

My guess is you can delete all `resource` related code, as they only servers to show you system resource usage information.

**Comment by shanshanhello** [comment]
Thank you for  your advice! but When I  build this project on Ubuntu,  the following problem arise:
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

**Comment by shanshanhello** [comment]
If it is convenient for you, can I contact you with WeChat. My wechat number is :littleDores. Thank you.

**Comment by uduse** [comment]
@shanshanhello [consult this](http://ask.xmodulo.com/importerror-no-module-named-setuptools.html). When you have errors with built-in packages, usually it's not library dependent. So googling the error message gives you the solution most of the time :)
