### ISSUE TITLE
Question: How to predict on unknown query

### ISSUE THREAD

**Issue by hkvision** [faneshion/MatchZoo#318]
Sorry for raising such question as I'm new to MatchZoo... I'm trying to use DRMM for a QA ranking problem and followed the preprocessing and training steps to train a model.
Wondering how can I do prediction for unknown data?
According to my understanding, in the preprocessing steps, all queries, docs and words are converted by ID. So if I'm given a new unseen query not in the training corpus, what ID can I assign to the query and what ID can I assign to the unseen words (if any) in the query?
I find the examples you provide generate train, val and test dataset at the same time for a given corpus beforehand, do I miss any example that illustrates the usage in the inference case I described above?

Really appreciate your help and thanks in advance!

**Comment by bwanglzu** [comment]
checkout #236 .

**Comment by hkvision** [comment]
@bwanglzu Thanks for your help. I have figured out how to do prediction :). I close this issue.

**Comment by wbj0110** [comment]
@hkvision Could you help me,I have the same question,give one query,and return top k documents,Could you show your code for me,Thanks very much
