### ISSUE TITLE
If I do not want to use pre-trained word embedding , how to do it 

### ISSUE THREAD

**Issue by danner1** [faneshion/MatchZoo#32]

**Comment by yangliuy** [comment]
You can choose not to pass the "embed_path" in the config file.

**Comment by danner1** [comment]
I want to run the mvlstm_classify model , Is to be changed in the mvlstm_classify.config file? However, there is no embed_path in this file.

**Comment by uduse** [comment]
checkout `mvlstm_wikiqa.config` for `embed_path`. Also, if you want to train a model without a pre-trained embedding, simply don't put that in your config, and a randomly initialized embedding will be generated for the model. You still need to config the embedding's shape, though.
