### ISSUE TITLE
matchpyramid

### ISSUE THREAD

**Issue by sjm1992st** [faneshion/MatchZoo#332]
I had read the paper, your model of matchpyramid is more simple ,why?

**Comment by pl8787** [comment]
You can add more convolutional layers if you needed, while the overall structure is similar.

**Comment by sjm1992st** [comment]
@pl8787 yeah...i add more convolutional layers , and I found the results were similar.I used multiple fixed-scale pooling instead of dynamic pooling in the last layer of convolution. Could you give me more information about dynamic pooling?

**Comment by pl8787** [comment]
The output shape of dynamic pooling is fixed, so it is useful for the data with variance length and easy for dense layer to learn.  Replacing dynamic pooling with fixed-scale pooling leads to performance drop.
We have implemented dynamic pooling in the MatchZoo.
