### ISSUE TITLE
How to run the MatchZoo in windows

### ISSUE THREAD

**Issue by r841009** [faneshion/MatchZoo#35]
I try to run setup.py with python
but it display error
this is its error message

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

C:\Users\MCLAB\AppData\Local\conda\conda\envs\Tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

My python edition is 3.5.4
and I have already installed the tensorflow library

**Comment by uduse** [comment]
I guess you need the full command: `python setup.py install`
