### ISSUE TITLE
Warning when make doc

### ISSUE THREAD

**Issue by wqh17101** [faneshion/MatchZoo#364]
![image](https://user-images.githubusercontent.com/26429138/46072657-84706580-c1b5-11e8-89af-040665d7829e.png)

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/46075130-1f6c3e00-c1bc-11e8-98c7-c4b46fc862f3.png)

**Comment by bwanglzu** [comment]
will look a bit later

**Comment by wqh17101** [comment]
https://github.com/sphinx-doc/sphinx/issues/5322
the error '_Any' object has no attribute '__origin__' seems like a bug of sphinx
the other error is our real bug.
