### ISSUE TITLE
sliding window unit

### ISSUE THREAD

**Issue by ZizhenWang** [faneshion/MatchZoo#366]
sliding window is useful in many models, like convolution-based models

**Comment by logicmd** [comment]
I thought we have used that in CDSSM, haven't we?
https://github.com/faneshion/MatchZoo/blob/ec0fef5e849f2439b08b2cf81e3192e39725eae0/examples/toy_example/config/cdssm_classify.config#L71

**Comment by ZizhenWang** [comment]
@logicmd Yes! But this unit is developed for version 2.0, which we want the users code more convenient and  efficient. And it is a general unit, not only for CDSSM, but also for some other models.
