### ISSUE TITLE
CDSSM output layer for classification

### ISSUE THREAD

**Issue by hexiang129** [faneshion/MatchZoo#373]
In CDSSM model implementation, it first calculate cosine similarity with Dot, which is a scalar, then it feeds the scalar to Dense with output size=2 and activation type being "softmax". This is really weird. How could one product a softmax for binary classification from a single scalar? Did I miss something here?

**Comment by bwanglzu** [comment]
check out section 4, this [paper](http://www.iro.umontreal.ca/~lisa/pointeurs/ir0895-he-2.pdf):

> Following [20], we first convert the semantic relevance score between a query and a positive document to the posterior probability of that document given the query through softmax..

**Comment by hexiang129** [comment]
Thanks. Yes. I am referring to task type=classification. I read the referred paragraph in the paper. To create the SoftMax, there needs to be some negative documents. (to simulate the capitable D in the paper).  Where shall I supply these negative documents in the current cdssm implementation?

**Comment by bwanglzu** [comment]
@hexiang129 It's not implemented in the current version of MatchZoo, but it will be there in MatchZoo 2.0.

Take a look our new [PairGenerator](https://github.com/faneshion/MatchZoo/blob/5d0d8e7f985c3e4f838744e2e8042e67ed46b7e8/matchzoo/generators/pair_generator.py#L57)

**Comment by hexiang129** [comment]
I see. thank you!
