### ISSUE TITLE
Use of python3

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#4]
Good morning,
I would like to use this toolkit to run experiments and develop/edit deep models, my question is: can I run it with python 3 (with the other requirements) or I should use Python 2.7?
Thanks

**Comment by faneshion** [comment]
Right now, it is built on Python 2.7, there may be some minor mistakes while using Python 3. The major difference comes from the character coding. We will deal with it in the future~

**Comment by thiziri** [comment]
Thank you, I'll use the required python2.7 version so.

**Comment by uduse** [comment]
It's a pain in the ass to deal with encodings with Python 2. Making the transition to Python 3 as soon as possible is advisable.
