### ISSUE TITLE
安装不成功，报错

### ISSUE THREAD

**Issue by yewenpeng** [faneshion/MatchZoo#42]
非常感谢开发组做出的努力，目前遇到2个问题
1.出了问题没法交流，能不能建个QQ群什么的，加微信加不上？
2.安装时报错：
Scanners.c
   正在创建库 build\temp.win32-2.7\Release\users\sony\appdata\local\temp\easy_in
stall-ctqurr\h5py-2.7.1\temp\easy_install-mfrl5r\Cython-0.27.3\Cython\Plex\Scann
ers.lib 和对象 build\temp.win32-2.7\Release\users\sony\appdata\local\temp\easy_i
nstall-ctqurr\h5py-2.7.1\temp\easy_install-mfrl5r\Cython-0.27.3\Cython\Plex\Scan
ners.exp
LINK : fatal error LNK1104: 无法打开文件“build\temp.win32-2.7\Release\users\son
y\appdata\local\temp\easy_install-ctqurr\h5py-2.7.1\temp\easy_install-mfrl5r\Cyt
hon-0.27.3\Cython\Plex\Scanners.pyd.manifest”
error: Setup script exited with error: command 'F:\\Program Files\\Microsoft Vis
ual Studio 9.0\\VC\\BIN\\link.exe' failed with exit status 1104

**Comment by uduse** [comment]
这个不像是 MatchZoo 的问题，应该就是 Cython 安装失败了。

**Comment by bwanglzu** [comment]
@yewenpeng 
Has your problem been solved?

I'll close this issue for now, if you still have further questions, please feel free to re-open it or create a new issue.

Best!
