### ISSUE TITLE
How to import my own text data, as well as through and matchzoo generate the specified data text file

### ISSUE THREAD

**Issue by LUPAGame** [faneshion/MatchZoo#45]
I have run some toy_example in matchzoo ,but  i want to train model and predict with my own text data, I  need your help please .

**Comment by yangliuy** [comment]
To run MatchZoo on your own data,  you just need to prepare your data to the input data format of MatchZoo. You can refer the document here: https://github.com/faneshion/MatchZoo/tree/master/data/toy_example

**Comment by LUPAGame** [comment]
Thanks for your answer,My previous thought was that I would type in a text to matchzoo and matchzoo would automatically process the input text that generated the corresponding format, such as corpus.txt and relation_train.txt, etc. Is this an idea that is wrong ,or i still have to customize the input text according to the format of matchzoo

**Comment by yangliuy** [comment]
Do you mean you want to use the trained model in an interactive way ? Currently MatchZoo does not support this. But you can process the predicted score file by MatchZoo for your own purpose. You should prepare the input data according to the input format of MatchZoo.
