### ISSUE TITLE
failure of "python setup.py install" ???

### ISSUE THREAD

**Issue by nanzhao** [faneshion/MatchZoo#47]
[root@training2 MatchZoo]# rm /usr/lib/python2.7/site-packages/MatchZoo-0.2.0-py2.7.egg
rm: remove regular file ‘/usr/lib/python2.7/site-packages/MatchZoo-0.2.0-py2.7.egg’? y
[root@training2 MatchZoo]# 
[root@training2 MatchZoo]# 
[root@training2 MatchZoo]# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to MatchZoo.egg-info/requires.txt
writing MatchZoo.egg-info/PKG-INFO
writing top-level names to MatchZoo.egg-info/top_level.txt
writing dependency_links to MatchZoo.egg-info/dependency_links.txt
reading manifest file 'MatchZoo.egg-info/SOURCES.txt'
writing manifest file 'MatchZoo.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/matchzoo
creating build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/list_generator.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/pair_generator.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/point_generator.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/preparation.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
copying build/lib/matchzoo/inputs/preprocess.py -> build/bdist.linux-x86_64/egg/matchzoo/inputs
creating build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/DynamicMaxPooling.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/Match.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/MatchTensor.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/NonMasking.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/SparseFullyConnectedLayer.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
copying build/lib/matchzoo/layers/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo/layers
creating build/bdist.linux-x86_64/egg/matchzoo/losses
copying build/lib/matchzoo/losses/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo/losses
copying build/lib/matchzoo/losses/rank_losses.py -> build/bdist.linux-x86_64/egg/matchzoo/losses
creating build/bdist.linux-x86_64/egg/matchzoo/metrics
copying build/lib/matchzoo/metrics/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo/metrics
copying build/lib/matchzoo/metrics/evaluations.py -> build/bdist.linux-x86_64/egg/matchzoo/metrics
copying build/lib/matchzoo/metrics/rank_evaluations.py -> build/bdist.linux-x86_64/egg/matchzoo/metrics
creating build/bdist.linux-x86_64/egg/matchzoo/utils
copying build/lib/matchzoo/utils/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo/utils
copying build/lib/matchzoo/utils/rank_io.py -> build/bdist.linux-x86_64/egg/matchzoo/utils
copying build/lib/matchzoo/utils/roc_auc.py -> build/bdist.linux-x86_64/egg/matchzoo/utils
copying build/lib/matchzoo/utils/utility.py -> build/bdist.linux-x86_64/egg/matchzoo/utils
copying build/lib/matchzoo/__init__.py -> build/bdist.linux-x86_64/egg/matchzoo
copying build/lib/matchzoo/main.py -> build/bdist.linux-x86_64/egg/matchzoo
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/list_generator.py to list_generator.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/pair_generator.py to pair_generator.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/point_generator.py to point_generator.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/preparation.py to preparation.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/inputs/preprocess.py to preprocess.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/DynamicMaxPooling.py to DynamicMaxPooling.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/Match.py to Match.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/MatchTensor.py to MatchTensor.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/NonMasking.py to NonMasking.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/SparseFullyConnectedLayer.py to SparseFullyConnectedLayer.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/layers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/losses/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/losses/rank_losses.py to rank_losses.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/metrics/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/metrics/evaluations.py to evaluations.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/metrics/rank_evaluations.py to rank_evaluations.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/utils/rank_io.py to rank_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/utils/roc_auc.py to roc_auc.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/utils/utility.py to utility.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/matchzoo/main.py to main.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying MatchZoo.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MatchZoo.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MatchZoo.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MatchZoo.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying MatchZoo.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/MatchZoo-0.2.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing MatchZoo-0.2.0-py2.7.egg
Copying MatchZoo-0.2.0-py2.7.egg to /usr/lib/python2.7/site-packages
Adding MatchZoo 0.2.0 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/MatchZoo-0.2.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    'tqdm >= 4.19.4'
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by bwanglzu** [comment]
This needed to be investigated.
