### ISSUE TITLE
classification task error

### ISSUE THREAD

**Issue by Chunlinx** [faneshion/MatchZoo#5]
I tried to run matchzoo to do classification task using command  
sudo python main.py --phase train --model_file ./models/matchpyramid_classify.config
sudo python main.py --phase predict --model_file ./models/matchpyramid_classify.config
but i got an error :"
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    main(sys.argv)
  File "main.py", line 298, in main
    predict(config)
  File "main.py", line 248, in predict
    list_counts = input_data['list_counts']
KeyError: 'list_counts'
"
would please tell me why this happend?

**Comment by pl8787** [comment]
We have fixed this bug in the newest version. You can download the newest version in the master branch.

**Comment by Chunlinx** [comment]
Hi, when i tried to run matchzoo on the the msrf dataset , I got an error indices[1,1]=10821 is not in the range(0,3273), I think this is due to the configure file. Could you please explain the parameters below : 
 "inputs": {
    "share": {
        "text1_corpus": "../data/example/classification/corpus_preprocessed.txt",
        "text2_corpus": "../data/example/classification/corpus_preprocessed.txt",
        "use_dpool": true,
        "fill_word": 3272,
        "embed_size": 100,
        "train_embed": true,
        "vocab_size": 3273,
        "target_mode": "classification",
        "class_num": 2,
        "text1_maxlen": 20,
        "text2_maxlen": 20
    },
what are fill_word embed_size, vocab_size mean? and how to determine these figures when applying to a certain dataset
Thank you !

**Comment by yangliuy** [comment]
fill_word: the max word id, which is vocab_size-1.
embed_size: the dimension of word embeddings.
vocab_size: the size of vocabulary.

A suitable configure is decided by the property of your data. For hyper-parameters in your model, you need to tune them with the validation set.

**Comment by yangliuy** [comment]
@Chunlinx  you can take a look at this file https://github.com/faneshion/MatchZoo/blob/master/data/example/readme.md

to understand the input data format of MatchZoo toolkit.

**Comment by yangliuy** [comment]
@Chunlinx Explanations about the parameters in config files can be found here : https://github.com/faneshion/MatchZoo/blob/master/matchzoo/models/readme.txt
