### ISSUE TITLE
有几个参数不太懂？能解答一下么？感谢！

### ISSUE THREAD

**Issue by yewenpeng** [faneshion/MatchZoo#52]
relation_train.txt  中我有200万行的数据对。
在XXX.config中，有几个参数如下：
"num_iters": 22300,
"query_per_iter": 70,
"batch_per_iter": 5,
 "batch_size": 100,

这几个分别是什么意思呢。不知道我理解是否对
batch_size是指一次batch跑100行数据
batch_per_iter是指一次跑5个batch
num_iters是指，一共跑22300次

那一共就会跑 5乘100乘22300 =11150000行数据对？

**Comment by yangliuy** [comment]
You can refer to our discussion on these parameters here: https://github.com/faneshion/MatchZoo/issues/40#issuecomment-360566397

**Comment by zhouzhouyang520** [comment]
1.首先数据的载入分两种方式：use_iter=True或者use_iter=False
2.前一种方式为数据部分载入(考虑到内存大小等的限制)，后一种方式为数据全部载入
3.每种载入方式，num_iters都是相同的意义，代表训练的周期，epoches
4.当数据部分载入时，每一次取的数据量为随机取query_per_iter个query，然后让这些query组成pairs
5.这批数据循环利用batch_per_iter这么多次，每次随机抽取batch_size这么多数据输入模型
具体代码见： MatchZoo/matchzoo/inputs/pair_generator.py

**Comment by guotong1988** [comment]
same question, thank you
