### ISSUE TITLE
How to achieve matchzoo distributed

### ISSUE THREAD

**Issue by LUPAGame** [faneshion/MatchZoo#53]
Hi ,i want to achieve matchzoo distributed by tensorflow. Is this feasible?If feasible, can you say  something about how to achieve it,thank you

**Comment by bwanglzu** [comment]
@faneshion Maybe at some point, integrate MatchZoo with [celery](https://github.com/celery/celery) or [dask](https://github.com/dask/dask) would be nice.

**Comment by bwanglzu** [comment]
I'll close this issue for now, if you have further question please feel free to re-open it or create a new one.
