### ISSUE TITLE
程序跑不通

### ISSUE THREAD

**Issue by shellbacksq** [faneshion/MatchZoo#59]
在模块安装好，数据下载好的情况下，按照readme中的代码示例跑了如下模型和得到结果:
anmm_wikiqa.config:IndexError: index 18670 is out of bounds for axis 0 with size 18670.
arci_wikiqa.config:IndexError: index 18672 is out of bounds for axis 0 with size 18670
arcii_wikiqa.config:IndexError: IndexError: index 18672 is out of bounds for axis 0 with size 18670
cdssm_wikiqa.config: Success!
cdssm_word_wikiqa.config:IndexError: index 18672 is out of bounds for axis 0 with size 18670
drmm_tks_wikiqa.config:IndexError: index 18676 is out of bounds for axis 0 with size 18670
drmm_wikiqa.config:IndexError: index 18670 is out of bounds for axis 0 with size 18670
dssm_wikiqa.config:Success!
duet_wikiqa.config:IndexError: index 18672 is out of bounds for axis 0 with size 18670
knrm_wikiqa.config:ValueError: could not broadcast input array from shape (50) into shape (300)
matchpyramid_wikiqa.config:IndexError: index 18676 is out of bounds for axis 0 with size 18670
mvlstm_wikiqa.config:IndexError: index 18672 is out of bounds for axis 0 with size 18670

基本报错信息都是如下：
Traceback (most recent call last):
  File "matchzoo/main.py", line 328, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 320, in main
    train(config)
  File "matchzoo/main.py", line 67, in train
    share_input_conf['embed'] = convert_embed_2_numpy(embed_dict, embed = embed)
  File "/home/sq/paper/MatchZoo/matchzoo/utils/rank_io.py", line 93, in convert_embed_2_numpy
    embed[k] = np.array(embed_dict[k])
IndexError: index 18672 is out of bounds for axis 0 with size 18670

难道是我打开方式不对？那为什么有些模型可以跑通呢？

**Comment by faneshion** [comment]
你这个问题是配置文件中的 vocab_size 配置不对，这个应该为 数据集文件夹中 word_dict.txt的行数，也就是词表的大小！

**Comment by shellbacksq** [comment]
了解，改成实际大小18678后就好了。
