### ISSUE TITLE
Varying input samples

### ISSUE THREAD

**Issue by tlinjordet** [faneshion/MatchZoo#60]
Hello, 
I am working on the DRMM applied to the WikiQA data set, 
trying to limit the number of labelled training samples before beginning training. 

This is what I do: 

1) 
I empty the folder
MatchZoo/examples/wikiqa/weights

2)
Following the sequence of commands in 
MatchZoo/data/WikiQA/run_data.sh,
after the command
python filter_query.py 
I am taking just 10 % of the lines from the file
MatchZoo/data/WikiQA/WikiQACorpus/WikiQA-dev-filtered.txt
(as generated by filter_query.py) to replace WikiQA-dev-filtered.txt.

Then I proceed with the command 
python transfer_to_mz_format.py
and the rest of the steps in run_data.sh, before proceeding with 

3)
python matchzoo/main.py --phase train --model_file examples/wikiqa/config/drmm_wikiqa.config
and
python matchzoo/main.py --phase predict --model_file examples/wikiqa/config/drmm_wikiqa.config

These are the results I get:
[Predict] @ predict [Predict] results:  ndcg@3=0.589837	map=0.609332	ndcg@5=0.650273
which is not very different from the results I get with just 
1) emptying weights folder as in step 1 above,
2) running run_data.sh without changes or interference, and
3) running training and prediction phases as in step 3 above. 
If I am in this way simply replicating the DRMM applied to WikiQA using MatchZoo, my best results
(i.e. closest to https://github.com/faneshion/MatchZoo#benchmark-results) 
have been:

[Predict] @ predict [Predict] results:  ndcg@3=0.609774	map=0.617857	ndcg@5=0.656974

Why do you think the first approach I described, of using only 10 % labelled training data, is making such a small difference?

**Comment by faneshion** [comment]
It's a very interesting question.  The number of training data may be connected to the number of trainable parameters in the model. While DRMM contains less than 1000 parameters, which may be trained with a small amount of data. Actually, I am not very sure about this. You can try more experiments to make deep investigate.

**Comment by tlinjordet** [comment]
Thank you for your comment. I have continued studying this since the last comment. 
Starting from 100 % of WikiQA data, to training with only 1% of the training and validation data (omitted randomly, question by question), DSSM performance goes from NDCG@5 = 0.602841 to NDCG@5 = 0.617537, and from MAP = 0.551042 to MAP=0.578807. That is, performance actually increases. How do you explain that?

**Comment by faneshion** [comment]
That's an interesting, slightly strange phenomenon. Increasing the dataset size decrease the performance instead, I am really curious about this. Have you conducted more experiments to investigate it? By the way, how does the performance of test data vary?  The only reason I could think of is that the distribution of 1% dataset is more consistent with the distribution of validation data. The original 100% training samples contain too many noises.
