### ISSUE TITLE
question about DRMM term gating

### ISSUE THREAD

**Issue by nsndimt** [faneshion/MatchZoo#64]
According to DRMM_PairGenerator, the text_1 is padded with  fill_word which is the last vocabulary.
In the DRMM the term gating score is computed with softmax on the whole vector and no mask is used.
I think the missing mask will lead to wrong term gating score, am I right?

**Comment by faneshion** [comment]
You are right! It is the difference compared with original DRMM.  This may affect the learned weight in the term gating network, and lead to poor performance. The right way is to apply mask as you have described.  Thanks for your suggestion. We will fixed it as soon as possible!

**Comment by nsndimt** [comment]
l think it can be fixed by adding an OOV which IDF is negative infinity, am I right?

**Comment by thiziri** [comment]
I couldn't figure out what change and where I should make it, would you like give more details please? because I'm using DRMM for re-ranking IR task and until now results are too bad.
Thanks

**Comment by faneshion** [comment]
@thiziri The difference lies in the padding.  For IR-tasks, the length of queries and docs both vary significantly. In MatchZoo, DRMM solved the document length problem by histogram mapping. However, we have to pad queries to a predefined length to enable the tensor operation. For example, if the max query length is 5 in the dataset, give a query "US China relationship",  we have to pad it to "US China relationship XX XX", here the "XX" is an OOV word just for padding. as the vector value of "XX" is randomly assigned, it also affect the learned weight in term gating network.

**Comment by thiziri** [comment]
Do you mean that I just have to tune the parameters "text1_maxlen" and "text2_maxlen" according to my dataset? An additional question about the random embeddings: how can I make a change in MatchZoo so that OOV words will be simply ignored instead of using random vectors? do the implementations in "matchzoo/models" generate an error if given word cannot be found in the embedding file?

**Comment by thiziri** [comment]
Okay, thanks @faneshion for your responses. I'll try to set OOV embedding vectors to zeros.

**Comment by bwanglzu** [comment]
I'm going to close this issue since it's has been solved.
