### ISSUE TITLE
Missing example data

### ISSUE THREAD

**Issue by imsure318** [faneshion/MatchZoo#7]
Hi, is it possible to provide the file of /data/example/ranking/word_triletter_map.txt?

**Comment by yangliuy** [comment]
@imsure318  You can refer to https://github.com/faneshion/MatchZoo/blob/master/examples/test_triletter_preprocess.py to generate this word_triletter_map.txt file. It is used in DSSM model, which use triletters as the vocabulary.

**Comment by guotong1988** [comment]
same question..
