### ISSUE TITLE
Why MZ uses the same file for "test" and "predict" ?

### ISSUE THREAD

**Issue by thiziri** [faneshion/MatchZoo#71]
Good afternoon,
Why all MZ models use the same file in "test" and "predict" ? like the following passage of drmm.config:

> "test": {
        "input_type": "DRMM_ListGenerator", 
        "phase": "EVAL",
        "batch_list": 10,
        "relation_file": "./data/WikiQA/relation_test.txt",
        "hist_feats_file": "./data/WikiQA/relation_test.hist-60.txt"
    },
    "predict": {
        "input_type": "DRMM_ListGenerator", 
        "phase": "PREDICT",
        "batch_list": 10,
        "relation_file": "./data/WikiQA/relation_test.txt",
        "hist_feats_file": "./data/WikiQA/relation_test.hist-60.txt"
    }

What is the difference if I use another file in "predict" that would contain more lines (tuples) then "relation_test.txt" ?
Thanks for answering

**Comment by faneshion** [comment]
Hi, the configuration is used for both training and predicting. In fact, it is no need to add 'test' for training phase, as we only use the 'train' and 'valid' to obtain the model. Then, we can use the trained model to predict the 'test' dataset. Here, we add 'test' in training phase, in this way, we can get the test performance without additional running. Thus, it saves time to rapidly tune parameters.

**Comment by thiziri** [comment]
Thanks for your responses. So, if I use a different corpus in .predict file, it will have no sense. Thanks again, your response helped me understand more.
