### ISSUE TITLE
What is the tech for preparing the candidate sentences at test time?

### ISSUE THREAD

**Issue by guotong1988** [faneshion/MatchZoo#72]
We need to select from the whole sentences first to get a small number of sentences for this match model.
Thank you!!
@faneshion @yangliuy @pl8787 @zhouzhouyang520 @HouJP @uduse

**Comment by faneshion** [comment]
A number of algorithm can be used to retrieval the candidate sentences, such as BM25, LM and so on.

**Comment by guotong1988** [comment]
可否具体点都列列，谢啦，在线等~
LM全称是？

**Comment by guotong1988** [comment]
language model做初筛的原理是怎样的呢……

**Comment by bwanglzu** [comment]
@guotong1988 Guess you're wiliing to select a set of most "important" sentences from one document, maybe `SumBasic` algorithm is a good choice (https://github.com/EthanMacdonald/SumBasic).

Personally believe `BM-25`/`TF-IDF`/`Language Model` is more suitable for select a set of "best matched" documents. If you're willing to do so, maybe [apache](https://github.com/apache/lucene-solr) and [elastic-search](https://github.com/elastic/elasticsearch) is good for you.

**Comment by faneshion** [comment]
BM25， LM都是一些高效的检索方法，一般在检索场景中用于候选文段的构建。如果你有大量的句子，可以先用@bwanglzu提到的lucene或elastic-search构建索引，然后选择一个算法，比如BM25或LM，对每一个句子检索top-k个候选的句子。

**Comment by guotong1988** [comment]
Thank you very much
