### ISSUE TITLE
vocab_size for cdssm

### ISSUE THREAD

**Issue by luyugao2** [faneshion/MatchZoo#77]
Is the vocab_size parameter for cdssm model the same as number of lines in triletter_dict.txt?

Thanks.

**Comment by faneshion** [comment]
Yes, you are definitely right.

**Comment by bwanglzu** [comment]
@luyugao2 Sorry for the late reply, hope your question has been solved, I'll close this issue for now. If you have further questions please feel free to open an new issue. Best.
