### ISSUE TITLE
What's the logic of the implementation of rank hinge loss?

### ISSUE THREAD

**Issue by StKlaas** [faneshion/MatchZoo#8]
Given a positive-labeled sample s1 and negative-labeled sample s2, the neural model would output two prediction values, which is further considered in the rank hinge loss. I got a little confused about the logic of computing this loss in keras when diving into the code in the MatchZoo, how do you handle this problem? Thank you in advance.

**Comment by yangliuy** [comment]
You can refer to Section 4.1 of http://www.bigdatalab.ac.cn/~gjf/papers/2016/CIKM2016a_guo.pdf, which shows the formula of rank hinge loss.

**Comment by faneshion** [comment]
@StKlaas In the data generator, such as matchzoo/inputs/pair_generator.py, we use X1 to store query information, and X2 to store doc information. And in X2, the pos document and neg document are in interleaved format. E.g. in a triple ( q1, d_pos, d_neg), X1 is (q1, q1) and X2 is (d_pos, d_neg).

**Comment by StKlaas** [comment]
@faneshion Thank you. I think I just ignored the fact that the loss is updated within a batch not a separate sample.
