### ISSUE TITLE
reproduction of the results

### ISSUE THREAD

**Issue by Chunlinx** [faneshion/MatchZoo#80]
Hi,
When I run the code on MSRP dataset ,I only got the accuracy result 66% not the same as the result on the paper 76%, what the basic parameter setup in your experiments?

**Comment by yangliuy** [comment]
For PI, we have incorporated results on QuoraQP (Quora Question Pairs) data insteads of MSRP in the readme file of MatchZoo. Which model did you refer to in your question ?

**Comment by bwanglzu** [comment]
Please check #99 .
