### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by bwanglzu** [faneshion/MatchZoo#82]
Realized a lot of issues came out related to `installation` error, I would suggest integrating MatchZoo with continuous integration.

@faneshion @yangliuy @uduse What do you think? There is a related PR #13 but apparently, CI does not necessarily limit to `flake8` testing, but also python `docstring` check, [PEP8](https://www.python.org/dev/peps/pep-0008/) check and unit tests.

If you're willing to do so, I suggest the project administrator could use his Github account to login [TravisCI](https://travis-ci.org/), which is a cloud-based integration test engine. And turn on CI for MatchZoo. It's always free for open source projects.

Every time when someone sends a PR to master branch, CI will automatically deploy all the dependencies on the server. It's a nice approach to reduce the technique debt.

**Comment by yangliuy** [comment]
I just tried to do the settings you suggested on travis-CI. But I am not very sure whether I did it in the correct way. I didn't use this platform before. Do you mean it could do automatic testing for MatchZoo after each commits ? In that case, do we need to prepare the testing cases ?

**Comment by bwanglzu** [comment]
@yangliuy Exactly, CI means for each commit, travis-ci will first run all the tests in the repository.

I noticed that MatchZoo is organized in a keras-like format, if you navigate to this [link](https://travis-ci.org/keras-team/keras), just open it you'll understand CI clearly.

**Comment by bwanglzu** [comment]
To run travis CI for matchzoo, you need to:
1. Activate MatchZoo in travis-ci
2. Add `.travis.yml` in project root directory for configuration, an example can be seen [here](https://github.com/keras-team/keras/blob/master/.travis.yml).
3. You can also add the so called "badge" into readme indicates that whether the project has passed all the unittests and integration tests, check keras [Readme](https://github.com/keras-team/keras), you can find a "badge" named "building|passing".
4.  I suggest to add  tests to MatchZoo, if we have tests covered all the models, we'll not encourter the situation appeared in #99 , clearly some commits has bugs, but we're not able to trace back to the exact commit.

**Comment by bwanglzu** [comment]
@yangliuy I've created something in #108 for initialization.

**Comment by yangliuy** [comment]
@bwanglzu I merged your pull request on this. Thank you for the detailed explanation! Good to know the steps of using Travis CI. It will require some additional work for the testing and configuration. But I also think it is very important to add unit testing/ integration testing if we want to enable MatchZoo to become an open source project with high quality. We can have more discussions on how to fix this part together with other developers @faneshion @pl8787 .

**Comment by bwanglzu** [comment]
@yangliuy Great! 

First of all we need to manage to pass the CI, even if we have no tests at the moment (because it's shows failing in Readme.md haha).

I'd suggest another useful tool named [codecov](`https://codecov.io/`), it's a free, open-source code coverage report that is able to check how many lines of code has been covered by unit tests. The ultimate situation is whenever a PR has been sent, it should first pass CI, then ensure this new added piece of code is covered by unit tests, then squash-and-merge.

**Comment by bwanglzu** [comment]
@yangliuy I think we have some problem here...basically the repository that should be added to Travis-CI should be `faneshion/MatchZoo` instead of `yangliuy / MatchZoo`.. Now Travis-CI is testing your sub-repository..

**Comment by yangliuy** [comment]
@bwanglzu Thanks! Got it. I will let @faneshion know about this to configure CI under his Travis-ci account.

**Comment by bwanglzu** [comment]
I've managed to pass CI on my forked repository: [link](https://travis-ci.org/bwanglzu/MatchZoo/jobs/382908503) for both Python 2.7 & 3.6, let's wait for @faneshion .

**Comment by yangliuy** [comment]
@bwanglzu Thank you! I have sent messages to @faneshion .

BTW, do you have WeChat account ? We would like to invite you to join our MatchZoo developer group on WeChat. What is your WeChat ID and email address ? Thanks!

**Comment by bwanglzu** [comment]
@yangliuy Yes I've added @faneshion on wechat , but not been invited yet. I'll send you an email now.

**Comment by bwanglzu** [comment]
@faneshion @yangliuy This issue will be closed , thanks for your work!

**Comment by fakekphan** [comment]
how to integrate ELMo embedding into MatchZoo?
