### ISSUE TITLE
how to set L2 regulization?

### ISSUE THREAD

**Issue by loveJasmine** [faneshion/MatchZoo#85]

**Comment by faneshion** [comment]
Most of models have a parameter named "activity_regularizer". You can set it to some pre-defined regularizers, such as "activity_regularizer=keras.regularizers.l2(0.01)".

**Comment by loveJasmine** [comment]
after I set regularizer for Conv2D, it reports:

Shapes must be equal rank, but are 4 and 0 for 'training/Adam/Assign_17' (op: 'Assign') with input shapes: [3,3,4,4], []

**Comment by faneshion** [comment]
These errors come out when you added the regularizer terms? Are you sure the `kernel_constraint` and `bias_regularizer` can be used like this? I have no experience with them, you can refer the keras docs get more information.
