### ISSUE TITLE
TREC file score

### ISSUE THREAD

**Issue by imsure318** [faneshion/MatchZoo#9]
The TREC file generated by using https://github.com/faneshion/MatchZoo/blob/master/examples/run_dssm_ranking.sh
seems have all the same scores of "1.000000". Could you plz help to double check?

**Comment by faneshion** [comment]
@imsure318 Thanks for your feedback. I will check it right now~

**Comment by faneshion** [comment]
Hi @imsure318, there have a bug at the Triletter_ListGenerator class in the previous version, and we have fixed it in the newest version. Thanks again for your feedback.
