### ISSUE TITLE
Confuse about read_data in rank_io.py

### ISSUE THREAD

**Issue by syw2014** [faneshion/MatchZoo#90]
Hi there ,as the readme file indicates corpus file , ["records the mapping from each text to a unique identifier called tid, along with a sequence of word identifiers contained in that text"](https://github.com/faneshion/MatchZoo),
which means the data in corpus file are two parts , the first is document id , the other was term id list eg: "T224 6 0 1 2 3 4 5", but I found your code to read data as bellow in [rank_io](https://github.com/faneshion/MatchZoo/blob/master/matchzoo/utils/rank_io.py) 

```
# Read Data Dict
def read_data(filename, word_dict = None):
    data = {}
    for line in open(filename):
        line = line.strip().split()
        tid = line[0]
        if word_dict is None:
            data[tid] = list(map(int, line[2:]))
        else:
            data[tid] = []
            for w in line[2:]:
                if w not in word_dict:
                    word_dict[w] = len(word_dict)
                data[tid].append(word_dict[w])
    print('[%s]\n\tData size: %s' % (filename, len(data)), end='\n')
    return data, word_dict
```
why you read word list from the third place not the second ? Have I missed something?

**Comment by thiziri** [comment]
Because the second place (6 in the example you gave) indicates the length of the document ;)
the text T224 has 6 words that are: 0, 1, 2, 3, 4 and 5.
That's all.
