### ISSUE TITLE
Please provide a requirement.txt for successfully running the program.

### ISSUE THREAD

**Issue by RamonYeung** [faneshion/MatchZoo#95]
I notice these model are written in Python 2.7+.
Though, what are the other package versions? 

Also, I add the provided wechat with some self-intro, and no response.
I want to join your community.

**Comment by bwanglzu** [comment]
In case you needed:

```python
keras >= 2.0.5
tensorflow >= 1.1.0
nltk >= 3.2.3
numpy >= 1.12.1
six >= 1.10.0
h5py >= 2.7.0
tqdm >= 4.19.4
```
